// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/python/util/protobuf/compare_test.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	tensorflow/python/util/protobuf/compare_test.proto

It has these top-level messages:
	Small
	Medium
	Large
	Labeled
	WithMap
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Enum int32

const (
	Enum_A Enum = 0
	Enum_B Enum = 1
	Enum_C Enum = 2
)

var Enum_name = map[int32]string{
	0: "A",
	1: "B",
	2: "C",
}
var Enum_value = map[string]int32{
	"A": 0,
	"B": 1,
	"C": 2,
}

func (x Enum) Enum() *Enum {
	p := new(Enum)
	*p = x
	return p
}
func (x Enum) String() string {
	return proto.EnumName(Enum_name, int32(x))
}
func (x *Enum) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Enum_value, data, "Enum")
	if err != nil {
		return err
	}
	*x = Enum(value)
	return nil
}
func (Enum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Small struct {
	Strings          []string `protobuf:"bytes,1,rep,name=strings" json:"strings,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Small) Reset()                    { *m = Small{} }
func (m *Small) String() string            { return proto.CompactTextString(m) }
func (*Small) ProtoMessage()               {}
func (*Small) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Small) GetStrings() []string {
	if m != nil {
		return m.Strings
	}
	return nil
}

type Medium struct {
	Int32S           []int32          `protobuf:"varint,1,rep,name=int32s" json:"int32s,omitempty"`
	Smalls           []*Small         `protobuf:"bytes,2,rep,name=smalls" json:"smalls,omitempty"`
	Groupa           []*Medium_GroupA `protobuf:"group,3,rep,name=GroupA,json=groupa" json:"groupa,omitempty"`
	Floats           []float32        `protobuf:"fixed32,6,rep,name=floats" json:"floats,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Medium) Reset()                    { *m = Medium{} }
func (m *Medium) String() string            { return proto.CompactTextString(m) }
func (*Medium) ProtoMessage()               {}
func (*Medium) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Medium) GetInt32S() []int32 {
	if m != nil {
		return m.Int32S
	}
	return nil
}

func (m *Medium) GetSmalls() []*Small {
	if m != nil {
		return m.Smalls
	}
	return nil
}

func (m *Medium) GetGroupa() []*Medium_GroupA {
	if m != nil {
		return m.Groupa
	}
	return nil
}

func (m *Medium) GetFloats() []float32 {
	if m != nil {
		return m.Floats
	}
	return nil
}

type Medium_GroupA struct {
	Groupb           []*Medium_GroupA_GroupB `protobuf:"group,4,rep,name=GroupB,json=groupb" json:"groupb,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *Medium_GroupA) Reset()                    { *m = Medium_GroupA{} }
func (m *Medium_GroupA) String() string            { return proto.CompactTextString(m) }
func (*Medium_GroupA) ProtoMessage()               {}
func (*Medium_GroupA) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Medium_GroupA) GetGroupb() []*Medium_GroupA_GroupB {
	if m != nil {
		return m.Groupb
	}
	return nil
}

type Medium_GroupA_GroupB struct {
	Strings          *string `protobuf:"bytes,5,req,name=strings" json:"strings,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Medium_GroupA_GroupB) Reset()                    { *m = Medium_GroupA_GroupB{} }
func (m *Medium_GroupA_GroupB) String() string            { return proto.CompactTextString(m) }
func (*Medium_GroupA_GroupB) ProtoMessage()               {}
func (*Medium_GroupA_GroupB) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0, 0} }

func (m *Medium_GroupA_GroupB) GetStrings() string {
	if m != nil && m.Strings != nil {
		return *m.Strings
	}
	return ""
}

type Large struct {
	String_          *string  `protobuf:"bytes,1,opt,name=string_,json=string" json:"string_,omitempty"`
	Int64_           *int64   `protobuf:"varint,2,opt,name=int64_,json=int64" json:"int64_,omitempty"`
	Float_           *float32 `protobuf:"fixed32,3,opt,name=float_,json=float" json:"float_,omitempty"`
	Bool_            *bool    `protobuf:"varint,4,opt,name=bool_,json=bool" json:"bool_,omitempty"`
	Enum_            *Enum    `protobuf:"varint,5,opt,name=enum_,json=enum,enum=compare_test.Enum" json:"enum_,omitempty"`
	Int64S           []int64  `protobuf:"varint,6,rep,name=int64s" json:"int64s,omitempty"`
	Medium           *Medium  `protobuf:"bytes,7,opt,name=medium" json:"medium,omitempty"`
	Small            *Small   `protobuf:"bytes,8,opt,name=small" json:"small,omitempty"`
	Double_          *float64 `protobuf:"fixed64,9,opt,name=double_,json=double" json:"double_,omitempty"`
	WithMap          *WithMap `protobuf:"bytes,10,opt,name=with_map,json=withMap" json:"with_map,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Large) Reset()                    { *m = Large{} }
func (m *Large) String() string            { return proto.CompactTextString(m) }
func (*Large) ProtoMessage()               {}
func (*Large) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Large) GetString_() string {
	if m != nil && m.String_ != nil {
		return *m.String_
	}
	return ""
}

func (m *Large) GetInt64_() int64 {
	if m != nil && m.Int64_ != nil {
		return *m.Int64_
	}
	return 0
}

func (m *Large) GetFloat_() float32 {
	if m != nil && m.Float_ != nil {
		return *m.Float_
	}
	return 0
}

func (m *Large) GetBool_() bool {
	if m != nil && m.Bool_ != nil {
		return *m.Bool_
	}
	return false
}

func (m *Large) GetEnum_() Enum {
	if m != nil && m.Enum_ != nil {
		return *m.Enum_
	}
	return Enum_A
}

func (m *Large) GetInt64S() []int64 {
	if m != nil {
		return m.Int64S
	}
	return nil
}

func (m *Large) GetMedium() *Medium {
	if m != nil {
		return m.Medium
	}
	return nil
}

func (m *Large) GetSmall() *Small {
	if m != nil {
		return m.Small
	}
	return nil
}

func (m *Large) GetDouble_() float64 {
	if m != nil && m.Double_ != nil {
		return *m.Double_
	}
	return 0
}

func (m *Large) GetWithMap() *WithMap {
	if m != nil {
		return m.WithMap
	}
	return nil
}

type Labeled struct {
	Required         *int32 `protobuf:"varint,1,req,name=required" json:"required,omitempty"`
	Optional         *int32 `protobuf:"varint,2,opt,name=optional" json:"optional,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Labeled) Reset()                    { *m = Labeled{} }
func (m *Labeled) String() string            { return proto.CompactTextString(m) }
func (*Labeled) ProtoMessage()               {}
func (*Labeled) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Labeled) GetRequired() int32 {
	if m != nil && m.Required != nil {
		return *m.Required
	}
	return 0
}

func (m *Labeled) GetOptional() int32 {
	if m != nil && m.Optional != nil {
		return *m.Optional
	}
	return 0
}

type WithMap struct {
	ValueMessage     map[int32]*Small  `protobuf:"bytes,1,rep,name=value_message,json=valueMessage" json:"value_message,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ValueString      map[string]string `protobuf:"bytes,2,rep,name=value_string,json=valueString" json:"value_string,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *WithMap) Reset()                    { *m = WithMap{} }
func (m *WithMap) String() string            { return proto.CompactTextString(m) }
func (*WithMap) ProtoMessage()               {}
func (*WithMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *WithMap) GetValueMessage() map[int32]*Small {
	if m != nil {
		return m.ValueMessage
	}
	return nil
}

func (m *WithMap) GetValueString() map[string]string {
	if m != nil {
		return m.ValueString
	}
	return nil
}

func init() {
	proto.RegisterType((*Small)(nil), "compare_test.Small")
	proto.RegisterType((*Medium)(nil), "compare_test.Medium")
	proto.RegisterType((*Medium_GroupA)(nil), "compare_test.Medium.GroupA")
	proto.RegisterType((*Medium_GroupA_GroupB)(nil), "compare_test.Medium.GroupA.GroupB")
	proto.RegisterType((*Large)(nil), "compare_test.Large")
	proto.RegisterType((*Labeled)(nil), "compare_test.Labeled")
	proto.RegisterType((*WithMap)(nil), "compare_test.WithMap")
	proto.RegisterEnum("compare_test.Enum", Enum_name, Enum_value)
}

func init() { proto.RegisterFile("tensorflow/python/util/protobuf/compare_test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 615 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x4f, 0x6f, 0xd3, 0x3e,
	0x18, 0xc7, 0x7f, 0x4e, 0xea, 0xb4, 0x75, 0xf7, 0x43, 0xc5, 0xdb, 0xc0, 0xea, 0x2e, 0xa6, 0x07,
	0x16, 0xfe, 0xac, 0x41, 0xd9, 0x34, 0xa1, 0x1d, 0x90, 0x56, 0x34, 0x21, 0xd0, 0x26, 0x24, 0x0f,
	0x81, 0xc4, 0x25, 0x4a, 0xa8, 0x97, 0x46, 0x4b, 0xe2, 0x90, 0x38, 0x9d, 0x7a, 0xe7, 0x45, 0xf1,
	0x12, 0x78, 0x49, 0x1c, 0x91, 0xed, 0x6c, 0x4b, 0xa1, 0x8c, 0x93, 0xf3, 0x7d, 0xf2, 0xc9, 0xf7,
	0xf1, 0xf3, 0x47, 0x41, 0xbe, 0xe4, 0x79, 0x25, 0xca, 0x8b, 0x54, 0x5c, 0x79, 0xc5, 0x52, 0xce,
	0x45, 0xee, 0xd5, 0x32, 0x49, 0xbd, 0xa2, 0x14, 0x52, 0x44, 0xf5, 0x85, 0xf7, 0x45, 0x64, 0x45,
	0x58, 0xf2, 0x40, 0xf2, 0x4a, 0x4e, 0x74, 0x14, 0x6f, 0xb4, 0x63, 0xe3, 0x47, 0x08, 0x9e, 0x67,
	0x61, 0x9a, 0x62, 0x82, 0xba, 0x95, 0x2c, 0x93, 0x3c, 0xae, 0x08, 0xa0, 0xb6, 0xdb, 0x67, 0xd7,
	0x72, 0xfc, 0xcd, 0x42, 0xce, 0x19, 0x9f, 0x25, 0x75, 0x86, 0x1f, 0x20, 0x27, 0xc9, 0xe5, 0xbe,
	0x6f, 0x18, 0xc8, 0x1a, 0x85, 0x9f, 0x21, 0xa7, 0x52, 0x2e, 0x15, 0xb1, 0xa8, 0xed, 0x0e, 0xfc,
	0xcd, 0xc9, 0x4a, 0x62, 0x9d, 0x81, 0x35, 0x08, 0xde, 0x47, 0x4e, 0x5c, 0x8a, 0xba, 0x08, 0x89,
	0x4d, 0x6d, 0x17, 0xf9, 0x3b, 0xab, 0xb0, 0x49, 0x35, 0x79, 0xa3, 0x90, 0x63, 0xd6, 0xa0, 0x2a,
	0xf3, 0x45, 0x2a, 0x42, 0x59, 0x11, 0x87, 0xda, 0xae, 0xc5, 0x1a, 0x35, 0x9a, 0x23, 0xc7, 0x90,
	0xf8, 0xa8, 0xb1, 0x8d, 0x48, 0x47, 0xdb, 0x8e, 0xef, 0xb0, 0x35, 0xc7, 0xb4, 0x71, 0x8f, 0x46,
	0xe3, 0xc6, 0x65, 0xda, 0x6e, 0x03, 0xa4, 0x56, 0xbb, 0x0d, 0x3f, 0x2c, 0x04, 0x4f, 0xc3, 0x32,
	0xe6, 0xf8, 0xe1, 0x35, 0x13, 0x10, 0x40, 0x81, 0xdb, 0x67, 0x8e, 0x91, 0x78, 0x5b, 0xb7, 0xe7,
	0xf0, 0x20, 0x20, 0x16, 0x05, 0xae, 0xcd, 0xa0, 0x56, 0x2a, 0xac, 0x6f, 0x1b, 0x10, 0x9b, 0x02,
	0xd7, 0x62, 0x50, 0x2b, 0xbc, 0x89, 0x60, 0x24, 0x44, 0x1a, 0x90, 0x0e, 0x05, 0x6e, 0x8f, 0x75,
	0x94, 0xc0, 0xbb, 0x08, 0xf2, 0xbc, 0xce, 0x02, 0x02, 0x29, 0x70, 0xef, 0xf9, 0x78, 0xb5, 0x88,
	0x93, 0xbc, 0xce, 0x58, 0x47, 0x01, 0xcd, 0x28, 0x0e, 0x0f, 0x4c, 0x43, 0x6c, 0xd6, 0x28, 0xfc,
	0x1c, 0x39, 0x99, 0x2e, 0x95, 0x74, 0x29, 0x70, 0x07, 0xfe, 0xd6, 0xba, 0x36, 0xb0, 0x86, 0xc1,
	0x4f, 0x10, 0xd4, 0x53, 0x21, 0x3d, 0x0d, 0xaf, 0x9d, 0x9b, 0x21, 0x54, 0xd5, 0x33, 0x51, 0x47,
	0x29, 0x0f, 0x48, 0x9f, 0x02, 0x17, 0x30, 0xc7, 0x48, 0xfc, 0x02, 0xf5, 0xae, 0x12, 0x39, 0x0f,
	0xb2, 0xb0, 0x20, 0x48, 0xdb, 0x6c, 0xaf, 0xda, 0x7c, 0x4a, 0xe4, 0xfc, 0x2c, 0x2c, 0x58, 0xf7,
	0xca, 0x3c, 0x8c, 0x8f, 0x51, 0xf7, 0x34, 0x8c, 0x78, 0xca, 0x67, 0x78, 0x84, 0x7a, 0x25, 0xff,
	0x5a, 0x27, 0x25, 0x9f, 0x11, 0x40, 0x2d, 0x17, 0xb2, 0x1b, 0xad, 0xde, 0x89, 0x42, 0x26, 0x22,
	0x0f, 0x53, 0xdd, 0x50, 0xc8, 0x6e, 0xf4, 0xf8, 0xbb, 0x85, 0xba, 0x8d, 0x2f, 0x3e, 0x45, 0xff,
	0x2f, 0xc2, 0xb4, 0xe6, 0x41, 0xc6, 0xab, 0x2a, 0x8c, 0xb9, 0x5e, 0xce, 0x81, 0xbf, 0xbb, 0xf6,
	0x16, 0x93, 0x8f, 0x0a, 0x3d, 0x33, 0xe4, 0x49, 0x2e, 0xcb, 0x25, 0xdb, 0x58, 0xb4, 0x42, 0xf8,
	0x2d, 0x32, 0x3a, 0x30, 0x43, 0x6d, 0x36, 0xfa, 0xf1, 0x1d, 0x66, 0xe7, 0x1a, 0x34, 0x5e, 0x83,
	0xc5, 0x6d, 0x64, 0xf4, 0x01, 0xdd, 0xff, 0x23, 0x1b, 0x1e, 0x22, 0xfb, 0x92, 0x2f, 0xf5, 0xe6,
	0x40, 0xa6, 0x1e, 0xd5, 0x10, 0xf4, 0x57, 0xba, 0xc8, 0xbf, 0x0d, 0x41, 0x13, 0x47, 0xd6, 0x4b,
	0x30, 0x7a, 0x85, 0x86, 0xbf, 0xa7, 0x6d, 0x9b, 0xf6, 0x8d, 0xe9, 0x56, 0xdb, 0xb4, 0xdf, 0xfa,
	0xfe, 0xe9, 0x0e, 0xea, 0xa8, 0x3d, 0xc2, 0x10, 0x81, 0xe3, 0xe1, 0x7f, 0xea, 0x98, 0x0e, 0x81,
	0x3a, 0x5e, 0x0f, 0xad, 0xe9, 0xfb, 0xcf, 0xef, 0xe2, 0x44, 0xce, 0xeb, 0x48, 0x5d, 0xc2, 0x9b,
	0x95, 0x7c, 0x79, 0xe9, 0xdd, 0xfe, 0x64, 0xf6, 0x2a, 0x5e, 0x2e, 0x92, 0x3c, 0xde, 0x8b, 0x85,
	0x57, 0x5c, 0xc6, 0xde, 0x3f, 0x7e, 0x3f, 0x3f, 0x01, 0xf8, 0x15, 0x00, 0x00, 0xff, 0xff, 0x3a,
	0x89, 0x36, 0xd2, 0xa3, 0x04, 0x00, 0x00,
}
