// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/grappler/costs/op_performance_data.proto

/*
Package costs is a generated protocol buffer package.

It is generated from these files:
	tensorflow/core/grappler/costs/op_performance_data.proto

It has these top-level messages:
	OpInfo
	OpPerformance
	OpPerformanceList
*/
package costs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import tensorflow3 "github.com/kuberlab/tfservable-proxy/pkg/tensorflow/core/framework"
import tensorflow1 "github.com/kuberlab/tfservable-proxy/pkg/tensorflow/core/framework"
import tensorflow2 "github.com/kuberlab/tfservable-proxy/pkg/tensorflow/core/framework"
import tensorflow4 "github.com/kuberlab/tfservable-proxy/pkg/tensorflow/core/framework"
import tensorflow5 "github.com/kuberlab/tfservable-proxy/pkg/tensorflow/core/protobuf"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Description of an operation as well as the parameters expected to impact its
// performance.
type OpInfo struct {
	// The operation name.  There may be custom parameters in attrs.
	Op string `protobuf:"bytes,1,opt,name=op" json:"op,omitempty"`
	// Custom parameters impacting the behavior of the op.
	Attr   map[string]*tensorflow4.AttrValue `protobuf:"bytes,2,rep,name=attr" json:"attr,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Inputs []*OpInfo_TensorProperties        `protobuf:"bytes,3,rep,name=inputs" json:"inputs,omitempty"`
	// Optional description of the op outputs
	Outputs []*OpInfo_TensorProperties `protobuf:"bytes,5,rep,name=outputs" json:"outputs,omitempty"`
	// Device on which the operation is run.
	Device *tensorflow5.DeviceProperties `protobuf:"bytes,4,opt,name=device" json:"device,omitempty"`
}

func (m *OpInfo) Reset()                    { *m = OpInfo{} }
func (m *OpInfo) String() string            { return proto.CompactTextString(m) }
func (*OpInfo) ProtoMessage()               {}
func (*OpInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OpInfo) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *OpInfo) GetAttr() map[string]*tensorflow4.AttrValue {
	if m != nil {
		return m.Attr
	}
	return nil
}

func (m *OpInfo) GetInputs() []*OpInfo_TensorProperties {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *OpInfo) GetOutputs() []*OpInfo_TensorProperties {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *OpInfo) GetDevice() *tensorflow5.DeviceProperties {
	if m != nil {
		return m.Device
	}
	return nil
}

// Input data types, shapes and values if known.
type OpInfo_TensorProperties struct {
	Dtype tensorflow2.DataType          `protobuf:"varint,1,opt,name=dtype,enum=tensorflow.DataType" json:"dtype,omitempty"`
	Shape *tensorflow1.TensorShapeProto `protobuf:"bytes,2,opt,name=shape" json:"shape,omitempty"`
	Value *tensorflow3.TensorProto      `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *OpInfo_TensorProperties) Reset()                    { *m = OpInfo_TensorProperties{} }
func (m *OpInfo_TensorProperties) String() string            { return proto.CompactTextString(m) }
func (*OpInfo_TensorProperties) ProtoMessage()               {}
func (*OpInfo_TensorProperties) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *OpInfo_TensorProperties) GetDtype() tensorflow2.DataType {
	if m != nil {
		return m.Dtype
	}
	return tensorflow2.DataType_DT_INVALID
}

func (m *OpInfo_TensorProperties) GetShape() *tensorflow1.TensorShapeProto {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *OpInfo_TensorProperties) GetValue() *tensorflow3.TensorProto {
	if m != nil {
		return m.Value
	}
	return nil
}

// Performance data for tensorflow operations
type OpPerformance struct {
	// The op
	Op *OpInfo `protobuf:"bytes,1,opt,name=op" json:"op,omitempty"`
	// The node name (optional). Makes it easier to associate the performance data
	// with a specific graph node.
	Node string `protobuf:"bytes,5,opt,name=node" json:"node,omitempty"`
	// Temporary memory used by this node (in bytes).
	TemporaryMemorySize int64 `protobuf:"varint,2,opt,name=temporary_memory_size,json=temporaryMemorySize" json:"temporary_memory_size,omitempty"`
	// Time it takes to run the op (in nanoseconds).
	ComputeCost int64 `protobuf:"varint,3,opt,name=compute_cost,json=computeCost" json:"compute_cost,omitempty"`
	// Analytical compute cost (in nanoseconds).
	ComputeTime int64 `protobuf:"varint,6,opt,name=compute_time,json=computeTime" json:"compute_time,omitempty"`
	// Analytical memory access cost (in nanoseconds).
	MemoryTime int64 `protobuf:"varint,7,opt,name=memory_time,json=memoryTime" json:"memory_time,omitempty"`
	// Percentage of theoretical compute performance.
	ComputeEfficiency float64 `protobuf:"fixed64,4,opt,name=compute_efficiency,json=computeEfficiency" json:"compute_efficiency,omitempty"`
	// Percentage of theoretical memory performance.
	MemoryEfficiency float64                 `protobuf:"fixed64,8,opt,name=memory_efficiency,json=memoryEfficiency" json:"memory_efficiency,omitempty"`
	OpMemory         *OpPerformance_OpMemory `protobuf:"bytes,9,opt,name=op_memory,json=opMemory" json:"op_memory,omitempty"`
}

func (m *OpPerformance) Reset()                    { *m = OpPerformance{} }
func (m *OpPerformance) String() string            { return proto.CompactTextString(m) }
func (*OpPerformance) ProtoMessage()               {}
func (*OpPerformance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OpPerformance) GetOp() *OpInfo {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *OpPerformance) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *OpPerformance) GetTemporaryMemorySize() int64 {
	if m != nil {
		return m.TemporaryMemorySize
	}
	return 0
}

func (m *OpPerformance) GetComputeCost() int64 {
	if m != nil {
		return m.ComputeCost
	}
	return 0
}

func (m *OpPerformance) GetComputeTime() int64 {
	if m != nil {
		return m.ComputeTime
	}
	return 0
}

func (m *OpPerformance) GetMemoryTime() int64 {
	if m != nil {
		return m.MemoryTime
	}
	return 0
}

func (m *OpPerformance) GetComputeEfficiency() float64 {
	if m != nil {
		return m.ComputeEfficiency
	}
	return 0
}

func (m *OpPerformance) GetMemoryEfficiency() float64 {
	if m != nil {
		return m.MemoryEfficiency
	}
	return 0
}

func (m *OpPerformance) GetOpMemory() *OpPerformance_OpMemory {
	if m != nil {
		return m.OpMemory
	}
	return nil
}

// Memory usage data for a tensorflow operation.
type OpPerformance_OpMemory struct {
	// The output information may have memory usage and output shapes.
	OutputMemory []int64 `protobuf:"varint,1,rep,packed,name=output_memory,json=outputMemory" json:"output_memory,omitempty"`
	// Temporary memory allocated by this node.
	HostTempMemory   int64 `protobuf:"varint,2,opt,name=host_temp_memory,json=hostTempMemory" json:"host_temp_memory,omitempty"`
	DeviceTempMemory int64 `protobuf:"varint,3,opt,name=device_temp_memory,json=deviceTempMemory" json:"device_temp_memory,omitempty"`
	// The persisted_memory doesn't include outputs.
	HostPersistentMemory   int64 `protobuf:"varint,4,opt,name=host_persistent_memory,json=hostPersistentMemory" json:"host_persistent_memory,omitempty"`
	DevicePersistentMemory int64 `protobuf:"varint,5,opt,name=device_persistent_memory,json=devicePersistentMemory" json:"device_persistent_memory,omitempty"`
}

func (m *OpPerformance_OpMemory) Reset()                    { *m = OpPerformance_OpMemory{} }
func (m *OpPerformance_OpMemory) String() string            { return proto.CompactTextString(m) }
func (*OpPerformance_OpMemory) ProtoMessage()               {}
func (*OpPerformance_OpMemory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *OpPerformance_OpMemory) GetOutputMemory() []int64 {
	if m != nil {
		return m.OutputMemory
	}
	return nil
}

func (m *OpPerformance_OpMemory) GetHostTempMemory() int64 {
	if m != nil {
		return m.HostTempMemory
	}
	return 0
}

func (m *OpPerformance_OpMemory) GetDeviceTempMemory() int64 {
	if m != nil {
		return m.DeviceTempMemory
	}
	return 0
}

func (m *OpPerformance_OpMemory) GetHostPersistentMemory() int64 {
	if m != nil {
		return m.HostPersistentMemory
	}
	return 0
}

func (m *OpPerformance_OpMemory) GetDevicePersistentMemory() int64 {
	if m != nil {
		return m.DevicePersistentMemory
	}
	return 0
}

// A collection of OpPerformance data points.
type OpPerformanceList struct {
	OpPerformance []*OpPerformance `protobuf:"bytes,1,rep,name=op_performance,json=opPerformance" json:"op_performance,omitempty"`
}

func (m *OpPerformanceList) Reset()                    { *m = OpPerformanceList{} }
func (m *OpPerformanceList) String() string            { return proto.CompactTextString(m) }
func (*OpPerformanceList) ProtoMessage()               {}
func (*OpPerformanceList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OpPerformanceList) GetOpPerformance() []*OpPerformance {
	if m != nil {
		return m.OpPerformance
	}
	return nil
}

func init() {
	proto.RegisterType((*OpInfo)(nil), "tensorflow.OpInfo")
	proto.RegisterType((*OpInfo_TensorProperties)(nil), "tensorflow.OpInfo.TensorProperties")
	proto.RegisterType((*OpPerformance)(nil), "tensorflow.OpPerformance")
	proto.RegisterType((*OpPerformance_OpMemory)(nil), "tensorflow.OpPerformance.OpMemory")
	proto.RegisterType((*OpPerformanceList)(nil), "tensorflow.OpPerformanceList")
}

func init() {
	proto.RegisterFile("tensorflow/core/grappler/costs/op_performance_data.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 708 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x95, 0x4f, 0x4f, 0xdb, 0x4a,
	0x14, 0xc5, 0xe5, 0x38, 0x09, 0xe4, 0x06, 0xa2, 0x30, 0x0f, 0x78, 0x7e, 0xd1, 0x93, 0x9a, 0x06,
	0xb5, 0x8a, 0x80, 0xc4, 0x28, 0x65, 0x81, 0x5a, 0x55, 0xfd, 0xcb, 0x02, 0xa9, 0x85, 0xc8, 0xa4,
	0x5d, 0x74, 0x63, 0x19, 0x67, 0x12, 0x2c, 0xb0, 0x67, 0x34, 0x9e, 0x80, 0xcc, 0xb7, 0xe9, 0x37,
	0xec, 0xae, 0xed, 0xae, 0xf2, 0x9d, 0xb1, 0x71, 0x42, 0xa1, 0xdd, 0x39, 0xf7, 0xfe, 0xce, 0x99,
	0x3b, 0xc7, 0xe3, 0x09, 0x1c, 0x48, 0x1a, 0xc5, 0x4c, 0x4c, 0x2e, 0xd9, 0xb5, 0xed, 0x33, 0x41,
	0xed, 0xa9, 0xf0, 0x38, 0xbf, 0xa4, 0xc2, 0xf6, 0x59, 0x2c, 0x63, 0x9b, 0x71, 0x97, 0x53, 0x31,
	0x61, 0x22, 0xf4, 0x22, 0x9f, 0xba, 0x63, 0x4f, 0x7a, 0x7d, 0x2e, 0x98, 0x64, 0x04, 0x6e, 0x95,
	0xad, 0xa7, 0x8b, 0x2e, 0x13, 0xe1, 0x85, 0xf4, 0x9a, 0x89, 0x0b, 0x5b, 0x75, 0x94, 0xa6, 0xb5,
	0xfb, 0x27, 0xce, 0x8d, 0xcf, 0x3d, 0x4e, 0x35, 0xfd, 0xe4, 0x01, 0x3a, 0xe1, 0x34, 0xd6, 0xd8,
	0xf6, 0xfd, 0x98, 0x27, 0xa5, 0x70, 0xaf, 0xbc, 0xcb, 0x59, 0x66, 0xb9, 0xb7, 0xc8, 0x62, 0xf9,
	0x6c, 0x36, 0xb1, 0xc7, 0xf4, 0x2a, 0xf0, 0xa9, 0xcb, 0x05, 0xe3, 0x54, 0xc8, 0x20, 0x73, 0xef,
	0x7c, 0x33, 0xa1, 0x7a, 0xc2, 0x8f, 0xa2, 0x09, 0x23, 0x0d, 0x28, 0x31, 0x6e, 0x19, 0x6d, 0xa3,
	0x5b, 0x73, 0x4a, 0x8c, 0x93, 0x3d, 0x28, 0xa7, 0x0b, 0x58, 0xa5, 0xb6, 0xd9, 0xad, 0x0f, 0xfe,
	0xef, 0xdf, 0x7a, 0xf7, 0x95, 0xa2, 0xff, 0x46, 0x4a, 0x71, 0x18, 0x49, 0x91, 0x38, 0x48, 0x92,
	0x17, 0x50, 0x0d, 0x22, 0x3e, 0x93, 0xb1, 0x65, 0xa2, 0x66, 0xeb, 0x37, 0x9a, 0x11, 0x56, 0x86,
	0xf9, 0x1c, 0x8e, 0x96, 0x90, 0x97, 0xb0, 0xc4, 0x66, 0x12, 0xd5, 0x95, 0xbf, 0x57, 0x67, 0x1a,
	0xb2, 0x0f, 0x55, 0xb5, 0x47, 0xab, 0xdc, 0x36, 0x16, 0xe7, 0x7d, 0x8f, 0x9d, 0xe2, 0xa2, 0x8a,
	0x6d, 0x1d, 0x43, 0x2d, 0xdf, 0x04, 0x69, 0x82, 0x79, 0x41, 0x13, 0x9d, 0x40, 0xfa, 0x48, 0x76,
	0xa0, 0x82, 0xf1, 0x5a, 0x25, 0xf4, 0xdc, 0x28, 0x7a, 0xa6, 0xba, 0xcf, 0x69, 0xd3, 0x51, 0xcc,
	0xf3, 0xd2, 0x81, 0xd1, 0xfa, 0x6a, 0x40, 0x73, 0x71, 0x46, 0xb2, 0x0d, 0x95, 0x71, 0xfa, 0x46,
	0xd1, 0xb9, 0x31, 0x58, 0x9f, 0x9b, 0xcc, 0x93, 0xde, 0x28, 0xe1, 0xd4, 0x51, 0x08, 0x19, 0x40,
	0x05, 0xcf, 0x88, 0x5e, 0x71, 0x6e, 0x17, 0xca, 0xf8, 0x34, 0x6d, 0x0f, 0xd3, 0x97, 0xe7, 0x28,
	0x94, 0xf4, 0xb2, 0x29, 0x4d, 0xd4, 0xfc, 0x7b, 0x57, 0xa3, 0x71, 0xa4, 0x3a, 0x3f, 0xcb, 0xb0,
	0x7a, 0xc2, 0x87, 0xb7, 0xc7, 0x9e, 0x74, 0xf2, 0x37, 0x5f, 0x1f, 0x90, 0xbb, 0xa9, 0xe3, 0x69,
	0x20, 0x50, 0x8e, 0xd8, 0x98, 0x5a, 0x15, 0x4c, 0x07, 0x9f, 0xc9, 0x00, 0x36, 0x24, 0x0d, 0x39,
	0x13, 0x9e, 0x48, 0xdc, 0x90, 0x86, 0x4c, 0x24, 0x6e, 0x1c, 0xdc, 0xa8, 0xe1, 0x4d, 0xe7, 0x9f,
	0xbc, 0xf9, 0x11, 0x7b, 0xa7, 0xc1, 0x0d, 0x25, 0x8f, 0x61, 0xc5, 0x67, 0x21, 0x9f, 0x49, 0xea,
	0xa6, 0x9f, 0x20, 0xce, 0x6c, 0x3a, 0x75, 0x5d, 0x7b, 0xc7, 0x62, 0x59, 0x44, 0x64, 0x10, 0x52,
	0xab, 0x3a, 0x87, 0x8c, 0x82, 0x90, 0x92, 0x47, 0x50, 0xd7, 0xeb, 0x21, 0xb1, 0x84, 0x04, 0xa8,
	0x12, 0x02, 0x3d, 0x20, 0x99, 0x07, 0x9d, 0x4c, 0x02, 0x3f, 0xa0, 0x91, 0x9f, 0xe0, 0xd1, 0x30,
	0x9c, 0x35, 0xdd, 0x39, 0xcc, 0x1b, 0x64, 0x07, 0xd6, 0xb4, 0x5f, 0x81, 0x5e, 0x46, 0xba, 0xa9,
	0x1a, 0x05, 0xf8, 0x15, 0xd4, 0x18, 0xd7, 0xfb, 0xb5, 0x6a, 0x98, 0x5a, 0x67, 0x3e, 0xb5, 0x42,
	0xb8, 0xfd, 0x13, 0xae, 0x76, 0xef, 0x2c, 0x33, 0xfd, 0xd4, 0xfa, 0x6e, 0xc0, 0x72, 0x56, 0x26,
	0x5b, 0xb0, 0xaa, 0xce, 0x70, 0xe6, 0x68, 0xb4, 0xcd, 0xae, 0xe9, 0xac, 0xa8, 0xa2, 0x86, 0xba,
	0xd0, 0x3c, 0x67, 0xb1, 0x74, 0xd3, 0x44, 0x33, 0x4e, 0x85, 0xdc, 0x48, 0xeb, 0x23, 0x1a, 0x66,
	0x76, 0xbb, 0x40, 0xf4, 0xb7, 0x5e, 0x64, 0x55, 0xca, 0x4d, 0xd5, 0x29, 0xd0, 0xfb, 0xb0, 0x89,
	0xbe, 0x9c, 0x8a, 0x38, 0x88, 0x25, 0x8d, 0xf2, 0x29, 0xca, 0xa8, 0x58, 0x4f, 0xbb, 0xc3, 0xbc,
	0xa9, 0x55, 0x07, 0x60, 0x65, 0xf7, 0xc9, 0x1d, 0x5d, 0x05, 0x75, 0x9b, 0xaa, 0xbf, 0xa8, 0xec,
	0x7c, 0x82, 0xb5, 0xb9, 0x74, 0x3e, 0x04, 0xb1, 0x24, 0xaf, 0xa1, 0x31, 0x7f, 0x0f, 0x63, 0x04,
	0xf5, 0xc1, 0x7f, 0xf7, 0x86, 0xea, 0xac, 0xb2, 0xe2, 0xcf, 0xb7, 0xc7, 0x5f, 0x8e, 0xa6, 0x81,
	0x3c, 0x9f, 0x9d, 0xf5, 0x7d, 0x16, 0xda, 0x63, 0x41, 0x93, 0xec, 0xc6, 0x4d, 0xb5, 0xbd, 0x98,
	0x8a, 0xab, 0x20, 0x9a, 0xf6, 0xa6, 0xcc, 0xe6, 0x17, 0x53, 0xfb, 0xe1, 0xff, 0x84, 0x1f, 0x86,
	0x71, 0x56, 0xc5, 0xcb, 0xf1, 0xd9, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xed, 0x94, 0xb3, 0xe0,
	0x3f, 0x06, 0x00, 0x00,
}
