// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/framework/allocation_description.proto

/*
Package framework is a generated protocol buffer package.

It is generated from these files:
	tensorflow/core/framework/allocation_description.proto
	tensorflow/core/framework/attr_value.proto
	tensorflow/core/framework/cost_graph.proto
	tensorflow/core/framework/device_attributes.proto
	tensorflow/core/framework/function.proto
	tensorflow/core/framework/graph.proto
	tensorflow/core/framework/graph_transfer_info.proto
	tensorflow/core/framework/kernel_def.proto
	tensorflow/core/framework/log_memory.proto
	tensorflow/core/framework/node_def.proto
	tensorflow/core/framework/op_def.proto
	tensorflow/core/framework/op_gen_overrides.proto
	tensorflow/core/framework/reader_base.proto
	tensorflow/core/framework/remote_fused_graph_execute_info.proto
	tensorflow/core/framework/resource_handle.proto
	tensorflow/core/framework/step_stats.proto
	tensorflow/core/framework/summary.proto
	tensorflow/core/framework/tensor.proto
	tensorflow/core/framework/tensor_description.proto
	tensorflow/core/framework/tensor_shape.proto
	tensorflow/core/framework/tensor_slice.proto
	tensorflow/core/framework/types.proto
	tensorflow/core/framework/variable.proto
	tensorflow/core/framework/versions.proto

It has these top-level messages:
	AllocationDescription
	AttrValue
	NameAttrList
	CostGraphDef
	DeviceLocality
	DeviceAttributes
	FunctionDefLibrary
	FunctionDef
	GradientDef
	GraphDef
	GraphTransferInfo
	KernelDef
	MemoryLogStep
	MemoryLogTensorAllocation
	MemoryLogTensorDeallocation
	MemoryLogTensorOutput
	MemoryLogRawAllocation
	MemoryLogRawDeallocation
	NodeDef
	OpDef
	OpDeprecation
	OpList
	OpGenOverride
	OpGenOverrides
	ReaderBaseState
	RemoteFusedGraphExecuteInfo
	ResourceHandle
	AllocatorMemoryUsed
	NodeOutput
	MemoryStats
	NodeExecStats
	DeviceStepStats
	StepStats
	SummaryDescription
	HistogramProto
	SummaryMetadata
	Summary
	TensorProto
	TensorDescription
	TensorShapeProto
	TensorSliceProto
	VariableDef
	SaveSliceInfoDef
	VersionDef
*/
package framework

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AllocationDescription struct {
	// Total number of bytes requested
	RequestedBytes int64 `protobuf:"varint,1,opt,name=requested_bytes,json=requestedBytes" json:"requested_bytes,omitempty"`
	// Total number of bytes allocated if known
	AllocatedBytes int64 `protobuf:"varint,2,opt,name=allocated_bytes,json=allocatedBytes" json:"allocated_bytes,omitempty"`
	// Name of the allocator used
	AllocatorName string `protobuf:"bytes,3,opt,name=allocator_name,json=allocatorName" json:"allocator_name,omitempty"`
	// Identifier of the allocated buffer if known
	AllocationId int64 `protobuf:"varint,4,opt,name=allocation_id,json=allocationId" json:"allocation_id,omitempty"`
	// Set if this tensor only has one remaining reference
	HasSingleReference bool `protobuf:"varint,5,opt,name=has_single_reference,json=hasSingleReference" json:"has_single_reference,omitempty"`
	// Address of the allocation.
	Ptr uint64 `protobuf:"varint,6,opt,name=ptr" json:"ptr,omitempty"`
}

func (m *AllocationDescription) Reset()                    { *m = AllocationDescription{} }
func (m *AllocationDescription) String() string            { return proto.CompactTextString(m) }
func (*AllocationDescription) ProtoMessage()               {}
func (*AllocationDescription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AllocationDescription) GetRequestedBytes() int64 {
	if m != nil {
		return m.RequestedBytes
	}
	return 0
}

func (m *AllocationDescription) GetAllocatedBytes() int64 {
	if m != nil {
		return m.AllocatedBytes
	}
	return 0
}

func (m *AllocationDescription) GetAllocatorName() string {
	if m != nil {
		return m.AllocatorName
	}
	return ""
}

func (m *AllocationDescription) GetAllocationId() int64 {
	if m != nil {
		return m.AllocationId
	}
	return 0
}

func (m *AllocationDescription) GetHasSingleReference() bool {
	if m != nil {
		return m.HasSingleReference
	}
	return false
}

func (m *AllocationDescription) GetPtr() uint64 {
	if m != nil {
		return m.Ptr
	}
	return 0
}

func init() {
	proto.RegisterType((*AllocationDescription)(nil), "tensorflow.AllocationDescription")
}

func init() {
	proto.RegisterFile("tensorflow/core/framework/allocation_description.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4b, 0xeb, 0x40,
	0x10, 0x87, 0xd9, 0xd7, 0xbe, 0xa2, 0x8b, 0x55, 0x09, 0x0a, 0x0b, 0x5e, 0x82, 0x22, 0xe6, 0xd2,
	0xac, 0x20, 0x78, 0xb7, 0xf4, 0xe2, 0x45, 0x4a, 0xbc, 0x79, 0x09, 0xdb, 0x64, 0xba, 0x5d, 0x9a,
	0xec, 0xc4, 0xd9, 0xad, 0xa5, 0x57, 0xff, 0x6a, 0xbd, 0x49, 0x5a, 0xbb, 0xf1, 0xa0, 0xb7, 0xe1,
	0x9b, 0x6f, 0x67, 0x87, 0xdf, 0xf0, 0x7b, 0x0f, 0xd6, 0x21, 0xcd, 0x2b, 0x5c, 0xcb, 0x02, 0x09,
	0xe4, 0x9c, 0x54, 0x0d, 0x6b, 0xa4, 0xa5, 0x54, 0x55, 0x85, 0x85, 0xf2, 0x06, 0x6d, 0x5e, 0x82,
	0x2b, 0xc8, 0x34, 0x6d, 0x9d, 0x36, 0x84, 0x1e, 0x23, 0xde, 0xbd, 0xbb, 0xfc, 0x64, 0xfc, 0xfc,
	0x21, 0xc8, 0x93, 0xce, 0x8d, 0x6e, 0xf8, 0x09, 0xc1, 0xeb, 0x0a, 0x9c, 0x87, 0x32, 0x9f, 0x6d,
	0x3c, 0x38, 0xc1, 0x62, 0x96, 0xf4, 0xb2, 0xe3, 0x80, 0xc7, 0x2d, 0x6d, 0xc5, 0xef, 0xef, 0x82,
	0xf8, 0x6f, 0x27, 0x06, 0xbc, 0x13, 0xaf, 0xf9, 0x9e, 0x20, 0xe5, 0x56, 0xd5, 0x20, 0x7a, 0x31,
	0x4b, 0x0e, 0xb3, 0x61, 0xa0, 0x4f, 0xaa, 0x86, 0xe8, 0x8a, 0x0f, 0x7f, 0xac, 0x6f, 0x4a, 0xd1,
	0xdf, 0x4e, 0x3b, 0xea, 0xe0, 0x63, 0x19, 0xdd, 0xf2, 0xb3, 0x85, 0x72, 0xb9, 0x33, 0x56, 0x57,
	0x90, 0x13, 0xcc, 0x81, 0xc0, 0x16, 0x20, 0xfe, 0xc7, 0x2c, 0x39, 0xc8, 0xa2, 0x85, 0x72, 0xcf,
	0xdb, 0x56, 0xb6, 0xef, 0x44, 0xa7, 0xbc, 0xd7, 0x78, 0x12, 0x83, 0x98, 0x25, 0xfd, 0xac, 0x2d,
	0xc7, 0xef, 0x8c, 0x0b, 0x24, 0x9d, 0x76, 0x71, 0xa4, 0x21, 0xc1, 0xf1, 0xc5, 0xaf, 0xa9, 0x4c,
	0xdb, 0x00, 0xdd, 0x94, 0xbd, 0x4c, 0xb4, 0xf1, 0x8b, 0xd5, 0x2c, 0x2d, 0xb0, 0x96, 0x25, 0xc1,
	0x66, 0x29, 0xbb, 0x29, 0x23, 0x07, 0xf4, 0x66, 0xac, 0x1e, 0x69, 0x94, 0xcd, 0x52, 0xcb, 0x3f,
	0xcf, 0xf4, 0xc1, 0xd8, 0x6c, 0xb0, 0xbd, 0xc9, 0xdd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x87,
	0xf5, 0x6d, 0x0c, 0xcd, 0x01, 0x00, 0x00,
}
