// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/framework/summary.proto

package framework

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Metadata associated with a series of Summary data
type SummaryDescription struct {
	// Hint on how plugins should process the data in this series.
	// Supported values include "scalar", "histogram", "image", "audio"
	TypeHint string `protobuf:"bytes,1,opt,name=type_hint,json=typeHint" json:"type_hint,omitempty"`
}

func (m *SummaryDescription) Reset()                    { *m = SummaryDescription{} }
func (m *SummaryDescription) String() string            { return proto.CompactTextString(m) }
func (*SummaryDescription) ProtoMessage()               {}
func (*SummaryDescription) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{0} }

func (m *SummaryDescription) GetTypeHint() string {
	if m != nil {
		return m.TypeHint
	}
	return ""
}

// Serialization format for histogram module in
// core/lib/histogram/histogram.h
type HistogramProto struct {
	Min        float64 `protobuf:"fixed64,1,opt,name=min" json:"min,omitempty"`
	Max        float64 `protobuf:"fixed64,2,opt,name=max" json:"max,omitempty"`
	Num        float64 `protobuf:"fixed64,3,opt,name=num" json:"num,omitempty"`
	Sum        float64 `protobuf:"fixed64,4,opt,name=sum" json:"sum,omitempty"`
	SumSquares float64 `protobuf:"fixed64,5,opt,name=sum_squares,json=sumSquares" json:"sum_squares,omitempty"`
	// Parallel arrays encoding the bucket boundaries and the bucket values.
	// bucket(i) is the count for the bucket i.  The range for
	// a bucket is:
	//   i == 0:  -DBL_MAX .. bucket_limit(0)
	//   i != 0:  bucket_limit(i-1) .. bucket_limit(i)
	BucketLimit []float64 `protobuf:"fixed64,6,rep,packed,name=bucket_limit,json=bucketLimit" json:"bucket_limit,omitempty"`
	Bucket      []float64 `protobuf:"fixed64,7,rep,packed,name=bucket" json:"bucket,omitempty"`
}

func (m *HistogramProto) Reset()                    { *m = HistogramProto{} }
func (m *HistogramProto) String() string            { return proto.CompactTextString(m) }
func (*HistogramProto) ProtoMessage()               {}
func (*HistogramProto) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{1} }

func (m *HistogramProto) GetMin() float64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *HistogramProto) GetMax() float64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *HistogramProto) GetNum() float64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *HistogramProto) GetSum() float64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *HistogramProto) GetSumSquares() float64 {
	if m != nil {
		return m.SumSquares
	}
	return 0
}

func (m *HistogramProto) GetBucketLimit() []float64 {
	if m != nil {
		return m.BucketLimit
	}
	return nil
}

func (m *HistogramProto) GetBucket() []float64 {
	if m != nil {
		return m.Bucket
	}
	return nil
}

// A SummaryMetadata encapsulates information on which plugins are able to make
// use of a certain summary value.
type SummaryMetadata struct {
	// A list of plugin data. A single summary value instance may be used by more
	// than 1 plugin.
	PluginData []*SummaryMetadata_PluginData `protobuf:"bytes,1,rep,name=plugin_data,json=pluginData" json:"plugin_data,omitempty"`
}

func (m *SummaryMetadata) Reset()                    { *m = SummaryMetadata{} }
func (m *SummaryMetadata) String() string            { return proto.CompactTextString(m) }
func (*SummaryMetadata) ProtoMessage()               {}
func (*SummaryMetadata) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{2} }

func (m *SummaryMetadata) GetPluginData() []*SummaryMetadata_PluginData {
	if m != nil {
		return m.PluginData
	}
	return nil
}

type SummaryMetadata_PluginData struct {
	// The name of the plugin this data pertains to.
	PluginName string `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName" json:"plugin_name,omitempty"`
	// The content to store for the plugin. The best practice is for this JSON
	// string to be the canonical JSON serialization of a protocol buffer
	// defined by the plugin. Converting that protobuf to and from JSON is the
	// responsibility of the plugin code, and is not enforced by
	// TensorFlow/TensorBoard.
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *SummaryMetadata_PluginData) Reset()                    { *m = SummaryMetadata_PluginData{} }
func (m *SummaryMetadata_PluginData) String() string            { return proto.CompactTextString(m) }
func (*SummaryMetadata_PluginData) ProtoMessage()               {}
func (*SummaryMetadata_PluginData) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{2, 0} }

func (m *SummaryMetadata_PluginData) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *SummaryMetadata_PluginData) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// A Summary is a set of named values to be displayed by the
// visualizer.
//
// Summaries are produced regularly during training, as controlled by
// the "summary_interval_secs" attribute of the training operation.
// Summaries are also produced at the end of an evaluation.
type Summary struct {
	// Set of values for the summary.
	Value []*Summary_Value `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *Summary) Reset()                    { *m = Summary{} }
func (m *Summary) String() string            { return proto.CompactTextString(m) }
func (*Summary) ProtoMessage()               {}
func (*Summary) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{3} }

func (m *Summary) GetValue() []*Summary_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Summary_Image struct {
	// Dimensions of the image.
	Height int32 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	Width  int32 `protobuf:"varint,2,opt,name=width" json:"width,omitempty"`
	// Valid colorspace values are
	//   1 - grayscale
	//   2 - grayscale + alpha
	//   3 - RGB
	//   4 - RGBA
	//   5 - DIGITAL_YUV
	//   6 - BGRA
	Colorspace int32 `protobuf:"varint,3,opt,name=colorspace" json:"colorspace,omitempty"`
	// Image data in encoded format.  All image formats supported by
	// image_codec::CoderUtil can be stored here.
	EncodedImageString []byte `protobuf:"bytes,4,opt,name=encoded_image_string,json=encodedImageString,proto3" json:"encoded_image_string,omitempty"`
}

func (m *Summary_Image) Reset()                    { *m = Summary_Image{} }
func (m *Summary_Image) String() string            { return proto.CompactTextString(m) }
func (*Summary_Image) ProtoMessage()               {}
func (*Summary_Image) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{3, 0} }

func (m *Summary_Image) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Summary_Image) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Summary_Image) GetColorspace() int32 {
	if m != nil {
		return m.Colorspace
	}
	return 0
}

func (m *Summary_Image) GetEncodedImageString() []byte {
	if m != nil {
		return m.EncodedImageString
	}
	return nil
}

type Summary_Audio struct {
	// Sample rate of the audio in Hz.
	SampleRate float32 `protobuf:"fixed32,1,opt,name=sample_rate,json=sampleRate" json:"sample_rate,omitempty"`
	// Number of channels of audio.
	NumChannels int64 `protobuf:"varint,2,opt,name=num_channels,json=numChannels" json:"num_channels,omitempty"`
	// Length of the audio in frames (samples per channel).
	LengthFrames int64 `protobuf:"varint,3,opt,name=length_frames,json=lengthFrames" json:"length_frames,omitempty"`
	// Encoded audio data and its associated RFC 2045 content type (e.g.
	// "audio/wav").
	EncodedAudioString []byte `protobuf:"bytes,4,opt,name=encoded_audio_string,json=encodedAudioString,proto3" json:"encoded_audio_string,omitempty"`
	ContentType        string `protobuf:"bytes,5,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
}

func (m *Summary_Audio) Reset()                    { *m = Summary_Audio{} }
func (m *Summary_Audio) String() string            { return proto.CompactTextString(m) }
func (*Summary_Audio) ProtoMessage()               {}
func (*Summary_Audio) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{3, 1} }

func (m *Summary_Audio) GetSampleRate() float32 {
	if m != nil {
		return m.SampleRate
	}
	return 0
}

func (m *Summary_Audio) GetNumChannels() int64 {
	if m != nil {
		return m.NumChannels
	}
	return 0
}

func (m *Summary_Audio) GetLengthFrames() int64 {
	if m != nil {
		return m.LengthFrames
	}
	return 0
}

func (m *Summary_Audio) GetEncodedAudioString() []byte {
	if m != nil {
		return m.EncodedAudioString
	}
	return nil
}

func (m *Summary_Audio) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

type Summary_Value struct {
	// This field is deprecated and will not be set.
	NodeName string `protobuf:"bytes,7,opt,name=node_name,json=nodeName" json:"node_name,omitempty"`
	// Tag name for the data. Used by TensorBoard plugins to organize data. Tags
	// are often organized by scope (which contains slashes to convey
	// hierarchy). For example: foo/bar/0
	Tag string `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	// Contains metadata on the summary value such as which plugins may use it.
	// Take note that many summary values may lack a metadata field. This is
	// because the FileWriter only keeps a metadata object on the first summary
	// value with a certain tag for each tag. TensorBoard then remembers which
	// tags are associated with which plugins. This saves space.
	Metadata *SummaryMetadata `protobuf:"bytes,9,opt,name=metadata" json:"metadata,omitempty"`
	// Value associated with the tag.
	//
	// Types that are valid to be assigned to Value:
	//	*Summary_Value_SimpleValue
	//	*Summary_Value_ObsoleteOldStyleHistogram
	//	*Summary_Value_Image
	//	*Summary_Value_Histo
	//	*Summary_Value_Audio
	//	*Summary_Value_Tensor
	Value isSummary_Value_Value `protobuf_oneof:"value"`
}

func (m *Summary_Value) Reset()                    { *m = Summary_Value{} }
func (m *Summary_Value) String() string            { return proto.CompactTextString(m) }
func (*Summary_Value) ProtoMessage()               {}
func (*Summary_Value) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{3, 2} }

type isSummary_Value_Value interface {
	isSummary_Value_Value()
}

type Summary_Value_SimpleValue struct {
	SimpleValue float32 `protobuf:"fixed32,2,opt,name=simple_value,json=simpleValue,oneof"`
}
type Summary_Value_ObsoleteOldStyleHistogram struct {
	ObsoleteOldStyleHistogram []byte `protobuf:"bytes,3,opt,name=obsolete_old_style_histogram,json=obsoleteOldStyleHistogram,proto3,oneof"`
}
type Summary_Value_Image struct {
	Image *Summary_Image `protobuf:"bytes,4,opt,name=image,oneof"`
}
type Summary_Value_Histo struct {
	Histo *HistogramProto `protobuf:"bytes,5,opt,name=histo,oneof"`
}
type Summary_Value_Audio struct {
	Audio *Summary_Audio `protobuf:"bytes,6,opt,name=audio,oneof"`
}
type Summary_Value_Tensor struct {
	Tensor *TensorProto `protobuf:"bytes,8,opt,name=tensor,oneof"`
}

func (*Summary_Value_SimpleValue) isSummary_Value_Value()               {}
func (*Summary_Value_ObsoleteOldStyleHistogram) isSummary_Value_Value() {}
func (*Summary_Value_Image) isSummary_Value_Value()                     {}
func (*Summary_Value_Histo) isSummary_Value_Value()                     {}
func (*Summary_Value_Audio) isSummary_Value_Value()                     {}
func (*Summary_Value_Tensor) isSummary_Value_Value()                    {}

func (m *Summary_Value) GetValue() isSummary_Value_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Summary_Value) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *Summary_Value) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Summary_Value) GetMetadata() *SummaryMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Summary_Value) GetSimpleValue() float32 {
	if x, ok := m.GetValue().(*Summary_Value_SimpleValue); ok {
		return x.SimpleValue
	}
	return 0
}

func (m *Summary_Value) GetObsoleteOldStyleHistogram() []byte {
	if x, ok := m.GetValue().(*Summary_Value_ObsoleteOldStyleHistogram); ok {
		return x.ObsoleteOldStyleHistogram
	}
	return nil
}

func (m *Summary_Value) GetImage() *Summary_Image {
	if x, ok := m.GetValue().(*Summary_Value_Image); ok {
		return x.Image
	}
	return nil
}

func (m *Summary_Value) GetHisto() *HistogramProto {
	if x, ok := m.GetValue().(*Summary_Value_Histo); ok {
		return x.Histo
	}
	return nil
}

func (m *Summary_Value) GetAudio() *Summary_Audio {
	if x, ok := m.GetValue().(*Summary_Value_Audio); ok {
		return x.Audio
	}
	return nil
}

func (m *Summary_Value) GetTensor() *TensorProto {
	if x, ok := m.GetValue().(*Summary_Value_Tensor); ok {
		return x.Tensor
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Summary_Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Summary_Value_OneofMarshaler, _Summary_Value_OneofUnmarshaler, _Summary_Value_OneofSizer, []interface{}{
		(*Summary_Value_SimpleValue)(nil),
		(*Summary_Value_ObsoleteOldStyleHistogram)(nil),
		(*Summary_Value_Image)(nil),
		(*Summary_Value_Histo)(nil),
		(*Summary_Value_Audio)(nil),
		(*Summary_Value_Tensor)(nil),
	}
}

func _Summary_Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Summary_Value)
	// value
	switch x := m.Value.(type) {
	case *Summary_Value_SimpleValue:
		b.EncodeVarint(2<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.SimpleValue)))
	case *Summary_Value_ObsoleteOldStyleHistogram:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.ObsoleteOldStyleHistogram)
	case *Summary_Value_Image:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Image); err != nil {
			return err
		}
	case *Summary_Value_Histo:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Histo); err != nil {
			return err
		}
	case *Summary_Value_Audio:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Audio); err != nil {
			return err
		}
	case *Summary_Value_Tensor:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Tensor); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Summary_Value.Value has unexpected type %T", x)
	}
	return nil
}

func _Summary_Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Summary_Value)
	switch tag {
	case 2: // value.simple_value
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Value = &Summary_Value_SimpleValue{math.Float32frombits(uint32(x))}
		return true, err
	case 3: // value.obsolete_old_style_histogram
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Value = &Summary_Value_ObsoleteOldStyleHistogram{x}
		return true, err
	case 4: // value.image
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Summary_Image)
		err := b.DecodeMessage(msg)
		m.Value = &Summary_Value_Image{msg}
		return true, err
	case 5: // value.histo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HistogramProto)
		err := b.DecodeMessage(msg)
		m.Value = &Summary_Value_Histo{msg}
		return true, err
	case 6: // value.audio
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Summary_Audio)
		err := b.DecodeMessage(msg)
		m.Value = &Summary_Value_Audio{msg}
		return true, err
	case 8: // value.tensor
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TensorProto)
		err := b.DecodeMessage(msg)
		m.Value = &Summary_Value_Tensor{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Summary_Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Summary_Value)
	// value
	switch x := m.Value.(type) {
	case *Summary_Value_SimpleValue:
		n += proto.SizeVarint(2<<3 | proto.WireFixed32)
		n += 4
	case *Summary_Value_ObsoleteOldStyleHistogram:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.ObsoleteOldStyleHistogram)))
		n += len(x.ObsoleteOldStyleHistogram)
	case *Summary_Value_Image:
		s := proto.Size(x.Image)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Summary_Value_Histo:
		s := proto.Size(x.Histo)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Summary_Value_Audio:
		s := proto.Size(x.Audio)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Summary_Value_Tensor:
		s := proto.Size(x.Tensor)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*SummaryDescription)(nil), "tensorflow.SummaryDescription")
	proto.RegisterType((*HistogramProto)(nil), "tensorflow.HistogramProto")
	proto.RegisterType((*SummaryMetadata)(nil), "tensorflow.SummaryMetadata")
	proto.RegisterType((*SummaryMetadata_PluginData)(nil), "tensorflow.SummaryMetadata.PluginData")
	proto.RegisterType((*Summary)(nil), "tensorflow.Summary")
	proto.RegisterType((*Summary_Image)(nil), "tensorflow.Summary.Image")
	proto.RegisterType((*Summary_Audio)(nil), "tensorflow.Summary.Audio")
	proto.RegisterType((*Summary_Value)(nil), "tensorflow.Summary.Value")
}

func init() { proto.RegisterFile("tensorflow/core/framework/summary.proto", fileDescriptor16) }

var fileDescriptor16 = []byte{
	// 754 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x5d, 0x93, 0xdb, 0x34,
	0x14, 0x5d, 0xaf, 0x71, 0xb2, 0xb9, 0x4e, 0x61, 0x47, 0xd3, 0x01, 0x37, 0x65, 0x20, 0xa4, 0x43,
	0xc9, 0x4b, 0x13, 0x36, 0x3c, 0xf0, 0xdc, 0xb0, 0x43, 0xc3, 0x0c, 0x1f, 0x3b, 0x4a, 0x87, 0x07,
	0x5e, 0x3c, 0x8a, 0xad, 0x3a, 0x9a, 0xb5, 0x24, 0x63, 0xc9, 0xdd, 0xe6, 0x17, 0xf0, 0x43, 0x78,
	0xe6, 0x1f, 0xf4, 0x95, 0xff, 0xc4, 0x23, 0xa3, 0x2b, 0x25, 0x1b, 0x98, 0xa6, 0x6f, 0xd2, 0xd1,
	0xb9, 0x3e, 0xd7, 0xe7, 0xe8, 0x0a, 0xbe, 0xb2, 0x5c, 0x19, 0xdd, 0xbe, 0xaa, 0xf5, 0xdd, 0xbc,
	0xd0, 0x2d, 0x9f, 0xbf, 0x6a, 0x99, 0xe4, 0x77, 0xba, 0xbd, 0x9d, 0x9b, 0x4e, 0x4a, 0xd6, 0xee,
	0x66, 0x4d, 0xab, 0xad, 0x26, 0x70, 0x4f, 0x1c, 0x3d, 0x3d, 0x5d, 0xe4, 0x4f, 0x7c, 0xcd, 0xe4,
	0x0a, 0xc8, 0xda, 0x7f, 0xe4, 0x9a, 0x9b, 0xa2, 0x15, 0x8d, 0x15, 0x5a, 0x91, 0xc7, 0x30, 0xb0,
	0xbb, 0x86, 0xe7, 0x5b, 0xa1, 0x6c, 0x16, 0x8d, 0xa3, 0xe9, 0x80, 0x5e, 0x38, 0x60, 0x25, 0x94,
	0x9d, 0xbc, 0x8d, 0xe0, 0xc3, 0x95, 0x30, 0x56, 0x57, 0x2d, 0x93, 0x37, 0xa8, 0x7c, 0x09, 0xb1,
	0x14, 0x0a, 0x99, 0x11, 0x75, 0x4b, 0x44, 0xd8, 0x9b, 0xec, 0x3c, 0x20, 0xec, 0x8d, 0x43, 0x54,
	0x27, 0xb3, 0xd8, 0x23, 0xaa, 0x93, 0x0e, 0x31, 0x9d, 0xcc, 0x3e, 0xf0, 0x88, 0xe9, 0x24, 0xf9,
	0x1c, 0x52, 0xd3, 0xc9, 0xdc, 0xfc, 0xde, 0xb1, 0x96, 0x9b, 0x2c, 0xc1, 0x13, 0x30, 0x9d, 0x5c,
	0x7b, 0x84, 0x7c, 0x09, 0xc3, 0x4d, 0x57, 0xdc, 0x72, 0x9b, 0xd7, 0x42, 0x0a, 0x9b, 0xf5, 0xc6,
	0xf1, 0x34, 0x5a, 0x9e, 0x5f, 0x46, 0x34, 0xf5, 0xf8, 0x8f, 0x0e, 0x26, 0x23, 0xe8, 0xf9, 0x6d,
	0xd6, 0x3f, 0x10, 0x02, 0x32, 0xf9, 0x33, 0x82, 0x8f, 0xc2, 0x2f, 0xff, 0xc4, 0x2d, 0x2b, 0x99,
	0x65, 0xe4, 0x05, 0xa4, 0x4d, 0xdd, 0x55, 0x42, 0xe5, 0x6e, 0x9b, 0x45, 0xe3, 0x78, 0x9a, 0x2e,
	0x9e, 0xce, 0xee, 0x3d, 0x9c, 0xfd, 0xaf, 0x62, 0x76, 0x83, 0xf4, 0x6b, 0x66, 0x19, 0x85, 0xe6,
	0xb0, 0x1e, 0xbd, 0x00, 0xb8, 0x3f, 0x71, 0xbf, 0x13, 0x3e, 0xab, 0x98, 0xe4, 0xc1, 0xc8, 0x40,
	0xff, 0x99, 0x49, 0x4e, 0x32, 0xe8, 0x17, 0x5a, 0x59, 0xae, 0x2c, 0x3a, 0x35, 0xa0, 0xfb, 0xed,
	0xe4, 0x6d, 0x0f, 0xfa, 0x41, 0x93, 0xcc, 0x21, 0x79, 0xcd, 0xea, 0x8e, 0x87, 0xbe, 0x1e, 0xbd,
	0xa3, 0xaf, 0xd9, 0xaf, 0x8e, 0x40, 0x3d, 0x6f, 0xf4, 0x47, 0x04, 0xc9, 0x0f, 0x92, 0x55, 0x9c,
	0x7c, 0x0c, 0xbd, 0x2d, 0x17, 0xd5, 0xd6, 0xa7, 0x98, 0xd0, 0xb0, 0x23, 0x0f, 0x21, 0xb9, 0x13,
	0xa5, 0xdd, 0xa2, 0x6c, 0x42, 0xfd, 0x86, 0x7c, 0x06, 0x50, 0xe8, 0x5a, 0xb7, 0xa6, 0x61, 0x05,
	0xc7, 0xa4, 0x12, 0x7a, 0x84, 0x90, 0xaf, 0xe1, 0x21, 0x57, 0x85, 0x2e, 0x79, 0x99, 0x0b, 0xf7,
	0xf9, 0xdc, 0xd8, 0x56, 0xa8, 0x0a, 0x13, 0x1c, 0x52, 0x12, 0xce, 0x50, 0x79, 0x8d, 0x27, 0xa3,
	0xbf, 0x23, 0x48, 0x9e, 0x77, 0xa5, 0xd0, 0x18, 0x2d, 0x93, 0x4d, 0xcd, 0xf3, 0x96, 0x59, 0xef,
	0xc5, 0x39, 0x05, 0x0f, 0x51, 0x66, 0x39, 0xf9, 0x02, 0x86, 0xaa, 0x93, 0x79, 0xb1, 0x65, 0x4a,
	0xf1, 0xda, 0x60, 0x67, 0x31, 0x4d, 0x55, 0x27, 0xbf, 0x0b, 0x10, 0x79, 0x02, 0x0f, 0x6a, 0xae,
	0x2a, 0xbb, 0xcd, 0xf1, 0x36, 0x1b, 0x6c, 0x31, 0xa6, 0x43, 0x0f, 0x7e, 0x8f, 0xd8, 0x71, 0x93,
	0xcc, 0x29, 0xbf, 0xbb, 0x49, 0x6c, 0xca, 0x37, 0xe9, 0x94, 0x83, 0xed, 0xb9, 0xbb, 0xe4, 0x78,
	0xed, 0x06, 0x34, 0x0d, 0xd8, 0xcb, 0x5d, 0xc3, 0x47, 0x7f, 0xc5, 0x90, 0xa0, 0xc5, 0x6e, 0x34,
	0x94, 0x2e, 0xb9, 0x4f, 0xb4, 0xef, 0x47, 0xc3, 0x01, 0x98, 0xe7, 0x25, 0xc4, 0x96, 0x55, 0x21,
	0x68, 0xb7, 0x24, 0xdf, 0xc2, 0x85, 0x0c, 0x77, 0x26, 0x1b, 0x8c, 0xa3, 0x69, 0xba, 0x78, 0xfc,
	0x9e, 0x6b, 0x45, 0x0f, 0x64, 0xf2, 0x04, 0x86, 0x46, 0xa0, 0x5f, 0x3e, 0x7b, 0x67, 0xc7, 0xf9,
	0xea, 0x8c, 0xa6, 0x1e, 0xf5, 0xcd, 0x3c, 0x87, 0x4f, 0xf5, 0xc6, 0xe8, 0x9a, 0x5b, 0x9e, 0xeb,
	0xba, 0xcc, 0x8d, 0xdd, 0xd5, 0x6e, 0x6a, 0xc3, 0x70, 0xa2, 0x3f, 0xc3, 0xd5, 0x19, 0x7d, 0xb4,
	0x67, 0xfd, 0x52, 0x97, 0x6b, 0xc7, 0x39, 0xcc, 0x2f, 0xb9, 0x82, 0x04, 0xb3, 0x44, 0x7f, 0x4e,
	0x5c, 0x2e, 0x4c, 0x74, 0x75, 0x46, 0x3d, 0x93, 0x2c, 0x20, 0x41, 0x09, 0x34, 0x2a, 0x5d, 0x8c,
	0x8e, 0x4b, 0xfe, 0xfb, 0x30, 0xb8, 0x1a, 0xa4, 0x3a, 0x19, 0x4c, 0x23, 0xeb, 0x9d, 0x96, 0xc1,
	0x4c, 0x5c, 0x09, 0x32, 0xc9, 0x15, 0xf4, 0x3c, 0x29, 0xbb, 0xc0, 0x9a, 0x4f, 0x8e, 0x6b, 0x5e,
	0xe2, 0x72, 0x2f, 0x12, 0x88, 0xcb, 0x7e, 0x98, 0x94, 0xa5, 0x85, 0x4c, 0xb7, 0xd5, 0x71, 0xc1,
	0xe1, 0xfd, 0x5b, 0x3e, 0x08, 0x7a, 0x58, 0x6c, 0x6e, 0xa2, 0xdf, 0xae, 0x2b, 0x61, 0xb7, 0xdd,
	0x66, 0x56, 0x68, 0x39, 0x2f, 0x5b, 0xbe, 0xdb, 0x3f, 0x91, 0xae, 0xee, 0x99, 0xe1, 0xed, 0x6b,
	0xa1, 0xaa, 0x67, 0x95, 0x9e, 0x37, 0xb7, 0xd5, 0xfc, 0xe4, 0xb3, 0xfa, 0x4f, 0x14, 0x6d, 0x7a,
	0xf8, 0xa6, 0x7e, 0xf3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0x91, 0xd2, 0x4d, 0xb2, 0x05,
	0x00, 0x00,
}
