// Code generated by protoc-gen-go. DO NOT EDIT.
// source: predict.ml_serving

package ml_serving

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	framework "github.com/kuberlab/tfservable-proxy/pkg/tensorflow/core/framework"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the ml_serving package it is being compiled against.
// A compilation error at this line likely means your copy of the
// ml_serving package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the ml_serving package

// Metadata for an inference request such as the model name and version.
type ModelSpec struct {
	// Required servable name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional version.
	Version int32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// A named signature to evaluate. If unspecified, the default signature will
	// be used.
	SignatureName        string   `protobuf:"bytes,3,opt,name=signature_name,json=signatureName,proto3" json:"signature_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelSpec) Reset()         { *m = ModelSpec{} }
func (m *ModelSpec) String() string { return proto.CompactTextString(m) }
func (*ModelSpec) ProtoMessage()    {}
func (*ModelSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_7497d3e8004dd709, []int{0}
}

func (m *ModelSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelSpec.Unmarshal(m, b)
}
func (m *ModelSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelSpec.Marshal(b, m, deterministic)
}
func (m *ModelSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelSpec.Merge(m, src)
}
func (m *ModelSpec) XXX_Size() int {
	return xxx_messageInfo_ModelSpec.Size(m)
}
func (m *ModelSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ModelSpec proto.InternalMessageInfo

func (m *ModelSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModelSpec) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ModelSpec) GetSignatureName() string {
	if m != nil {
		return m.SignatureName
	}
	return ""
}

type PredictRequest struct {
	// Model Specification. If version is not specified, will use the latest
	// (numerical) version.
	ModelSpec *ModelSpec `protobuf:"bytes,1,opt,name=model_spec,json=modelSpec,proto3" json:"model_spec,omitempty"`
	// Input tensors.
	// Names of input tensor are alias names. The mapping from aliases to real
	// input tensor names is stored in the SavedModel export as a prediction
	// SignatureDef under the 'inputs' field.
	Inputs map[string]*framework.TensorProto `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Output filter.
	// Names specified are alias names. The mapping from aliases to real output
	// tensor names is stored in the SavedModel export as a prediction
	// SignatureDef under the 'outputs' field.
	// Only tensors specified here will be run/fetched and returned, with the
	// exception that when none is specified, all tensors specified in the
	// named signature will be run/fetched and returned.
	OutputFilter         []string `protobuf:"bytes,3,rep,name=output_filter,json=outputFilter,proto3" json:"output_filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictRequest) Reset()         { *m = PredictRequest{} }
func (m *PredictRequest) String() string { return proto.CompactTextString(m) }
func (*PredictRequest) ProtoMessage()    {}
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7497d3e8004dd709, []int{1}
}

func (m *PredictRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictRequest.Unmarshal(m, b)
}
func (m *PredictRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictRequest.Marshal(b, m, deterministic)
}
func (m *PredictRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictRequest.Merge(m, src)
}
func (m *PredictRequest) XXX_Size() int {
	return xxx_messageInfo_PredictRequest.Size(m)
}
func (m *PredictRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PredictRequest proto.InternalMessageInfo

func (m *PredictRequest) GetModelSpec() *ModelSpec {
	if m != nil {
		return m.ModelSpec
	}
	return nil
}

func (m *PredictRequest) GetInputs() map[string]*framework.TensorProto {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *PredictRequest) GetOutputFilter() []string {
	if m != nil {
		return m.OutputFilter
	}
	return nil
}

type PredictJSONData struct {
	// JSON inputs as string
	JsonString           string   `protobuf:"bytes,1,opt,name=json_string,json=jsonString,proto3" json:"json_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictJSONData) Reset()         { *m = PredictJSONData{} }
func (m *PredictJSONData) String() string { return proto.CompactTextString(m) }
func (*PredictJSONData) ProtoMessage()    {}
func (*PredictJSONData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7497d3e8004dd709, []int{2}
}

func (m *PredictJSONData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictJSONData.Unmarshal(m, b)
}
func (m *PredictJSONData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictJSONData.Marshal(b, m, deterministic)
}
func (m *PredictJSONData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictJSONData.Merge(m, src)
}
func (m *PredictJSONData) XXX_Size() int {
	return xxx_messageInfo_PredictJSONData.Size(m)
}
func (m *PredictJSONData) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictJSONData.DiscardUnknown(m)
}

var xxx_messageInfo_PredictJSONData proto.InternalMessageInfo

func (m *PredictJSONData) GetJsonString() string {
	if m != nil {
		return m.JsonString
	}
	return ""
}

// Response for PredictRequest on successful run.
type PredictResponse struct {
	// Effective Model Specification used to process PredictRequest.
	ModelSpec *ModelSpec `protobuf:"bytes,2,opt,name=model_spec,json=modelSpec,proto3" json:"model_spec,omitempty"`
	// Output tensors.
	Outputs              map[string]*framework.TensorProto `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *PredictResponse) Reset()         { *m = PredictResponse{} }
func (m *PredictResponse) String() string { return proto.CompactTextString(m) }
func (*PredictResponse) ProtoMessage()    {}
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7497d3e8004dd709, []int{3}
}

func (m *PredictResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictResponse.Unmarshal(m, b)
}
func (m *PredictResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictResponse.Marshal(b, m, deterministic)
}
func (m *PredictResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictResponse.Merge(m, src)
}
func (m *PredictResponse) XXX_Size() int {
	return xxx_messageInfo_PredictResponse.Size(m)
}
func (m *PredictResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PredictResponse proto.InternalMessageInfo

func (m *PredictResponse) GetModelSpec() *ModelSpec {
	if m != nil {
		return m.ModelSpec
	}
	return nil
}

func (m *PredictResponse) GetOutputs() map[string]*framework.TensorProto {
	if m != nil {
		return m.Outputs
	}
	return nil
}

// Test request
type TestRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRequest) Reset()         { *m = TestRequest{} }
func (m *TestRequest) String() string { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()    {}
func (*TestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7497d3e8004dd709, []int{4}
}

func (m *TestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequest.Unmarshal(m, b)
}
func (m *TestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequest.Marshal(b, m, deterministic)
}
func (m *TestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequest.Merge(m, src)
}
func (m *TestRequest) XXX_Size() int {
	return xxx_messageInfo_TestRequest.Size(m)
}
func (m *TestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequest proto.InternalMessageInfo

func (m *TestRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Test Response
type TestResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestResponse) Reset()         { *m = TestResponse{} }
func (m *TestResponse) String() string { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()    {}
func (*TestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7497d3e8004dd709, []int{5}
}

func (m *TestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResponse.Unmarshal(m, b)
}
func (m *TestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResponse.Marshal(b, m, deterministic)
}
func (m *TestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResponse.Merge(m, src)
}
func (m *TestResponse) XXX_Size() int {
	return xxx_messageInfo_TestResponse.Size(m)
}
func (m *TestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestResponse proto.InternalMessageInfo

func (m *TestResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ModelSpec)(nil), "ml_serving.ModelSpec")
	proto.RegisterType((*PredictRequest)(nil), "ml_serving.PredictRequest")
	proto.RegisterMapType((map[string]*framework.TensorProto)(nil), "ml_serving.PredictRequest.InputsEntry")
	proto.RegisterType((*PredictJSONData)(nil), "ml_serving.PredictJSONData")
	proto.RegisterType((*PredictResponse)(nil), "ml_serving.PredictResponse")
	proto.RegisterMapType((map[string]*framework.TensorProto)(nil), "ml_serving.PredictResponse.OutputsEntry")
	proto.RegisterType((*TestRequest)(nil), "ml_serving.TestRequest")
	proto.RegisterType((*TestResponse)(nil), "ml_serving.TestResponse")
}

func init() { proto.RegisterFile("predict.ml_serving", fileDescriptor_7497d3e8004dd709) }

var fileDescriptor_7497d3e8004dd709 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xdf, 0x6e, 0x94, 0x40,
	0x14, 0xc6, 0x0b, 0xb4, 0xdd, 0xec, 0x81, 0x56, 0x9d, 0xc4, 0x48, 0x30, 0xd1, 0x0d, 0x46, 0xe5,
	0x46, 0x2e, 0xd0, 0x18, 0xa3, 0x89, 0x17, 0x9b, 0x6a, 0x52, 0xff, 0xb4, 0x1b, 0xe8, 0x3d, 0xb2,
	0xdb, 0xe3, 0x06, 0x0b, 0x33, 0x38, 0x33, 0x6c, 0xd2, 0xd7, 0xf1, 0xc9, 0xf4, 0x49, 0x34, 0xcc,
	0x0c, 0x88, 0xb5, 0x6d, 0xbc, 0xf0, 0x8e, 0x39, 0xe7, 0xfb, 0x38, 0xdf, 0xfc, 0x66, 0x06, 0xf6,
	0x1a, 0x8e, 0xa7, 0xe5, 0x4a, 0xc6, 0x0d, 0x67, 0x92, 0x11, 0xa8, 0xab, 0x5c, 0x20, 0xdf, 0x94,
	0x74, 0x1d, 0x78, 0x12, 0xa9, 0x60, 0x5c, 0x77, 0xc2, 0x4f, 0x30, 0xfd, 0xc8, 0x4e, 0xb1, 0xca,
	0x1a, 0x5c, 0x11, 0x02, 0xdb, 0xb4, 0xa8, 0xd1, 0xb7, 0x66, 0x56, 0x34, 0x4d, 0xd5, 0x37, 0xf1,
	0x61, 0xb2, 0x41, 0x2e, 0x4a, 0x46, 0x7d, 0x7b, 0x66, 0x45, 0x3b, 0x69, 0xbf, 0x24, 0x0f, 0x61,
	0x5f, 0x94, 0x6b, 0x5a, 0xc8, 0x96, 0x63, 0xae, 0x7c, 0x8e, 0xf2, 0xed, 0x0d, 0xd5, 0xa3, 0xa2,
	0xc6, 0xf0, 0xa7, 0x05, 0xfb, 0x0b, 0x9d, 0x26, 0xc5, 0xaf, 0x2d, 0x0a, 0x49, 0x9e, 0x01, 0xd4,
	0xdd, 0xd0, 0x5c, 0x34, 0xb8, 0x52, 0xd3, 0xdc, 0xe4, 0x76, 0xfc, 0x3b, 0x63, 0x3c, 0x44, 0x4a,
	0xa7, 0xf5, 0x90, 0xee, 0x35, 0xec, 0x96, 0xb4, 0x69, 0xa5, 0xf0, 0xed, 0x99, 0x13, 0xb9, 0xc9,
	0xa3, 0xb1, 0xe3, 0xcf, 0x09, 0xf1, 0xa1, 0x12, 0xbe, 0xa1, 0x92, 0x9f, 0xa7, 0xc6, 0x45, 0x1e,
	0xc0, 0x1e, 0x6b, 0x65, 0xd3, 0xca, 0xfc, 0x73, 0x59, 0x49, 0xe4, 0xbe, 0x33, 0x73, 0xa2, 0x69,
	0xea, 0xe9, 0xe2, 0x5b, 0x55, 0x0b, 0x52, 0x70, 0x47, 0x5e, 0x72, 0x13, 0x9c, 0x33, 0x3c, 0x37,
	0x40, 0xba, 0x4f, 0xf2, 0x04, 0x76, 0x36, 0x45, 0xd5, 0xa2, 0xa2, 0xe1, 0x26, 0x77, 0xc6, 0x21,
	0x4e, 0x14, 0xd9, 0x45, 0x07, 0x36, 0xd5, 0xaa, 0x97, 0xf6, 0x0b, 0x2b, 0x4c, 0xe0, 0x86, 0x89,
	0xf7, 0x2e, 0x3b, 0x3e, 0x3a, 0x28, 0x64, 0x41, 0xee, 0x83, 0xfb, 0x45, 0x30, 0x9a, 0x0b, 0xc9,
	0x4b, 0xba, 0x36, 0xff, 0x87, 0xae, 0x94, 0xa9, 0x4a, 0xf8, 0xdd, 0x1a, 0x4c, 0x29, 0x8a, 0x86,
	0x51, 0x81, 0x17, 0xb0, 0xd9, 0xff, 0x88, 0x6d, 0x0e, 0x13, 0xbd, 0x43, 0xe1, 0x5b, 0x8a, 0x5b,
	0x74, 0x29, 0x37, 0x3d, 0x23, 0x3e, 0xd6, 0x52, 0x4d, 0xae, 0x37, 0x06, 0x19, 0x78, 0xe3, 0xc6,
	0xff, 0xc1, 0xf2, 0x18, 0xdc, 0x13, 0x14, 0xc3, 0xa5, 0xf0, 0x61, 0x52, 0xa3, 0x10, 0xc5, 0xba,
	0xbf, 0x7f, 0xfd, 0x32, 0x8c, 0xc0, 0xd3, 0x42, 0xc3, 0xe1, 0x4a, 0x65, 0xf2, 0xc3, 0x82, 0x5b,
	0x66, 0x47, 0x25, 0xa3, 0x59, 0x37, 0x7f, 0x85, 0xe4, 0x00, 0x26, 0xa6, 0x48, 0x82, 0xab, 0xef,
	0x4c, 0x70, 0xf7, 0x1a, 0x2e, 0xe1, 0x16, 0x39, 0x04, 0x77, 0x74, 0x8a, 0xe4, 0x32, 0x75, 0x7f,
	0xbc, 0xc1, 0x75, 0xcd, 0x70, 0x8b, 0xbc, 0x82, 0xed, 0x6e, 0x43, 0xe4, 0x02, 0xa5, 0x81, 0x45,
	0xe0, 0xff, 0xdd, 0xe8, 0x73, 0xcc, 0x9f, 0xc3, 0xbd, 0x92, 0xc5, 0x67, 0xed, 0x12, 0x79, 0x55,
	0x2c, 0xc7, 0x42, 0xf3, 0xe6, 0xe7, 0x9e, 0x99, 0xa8, 0x88, 0x2f, 0xac, 0x6f, 0xb6, 0xf3, 0xfe,
	0xc3, 0x7c, 0xb9, 0xab, 0x1e, 0xfc, 0xd3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xab, 0x38, 0xb0,
	0xee, 0x1b, 0x04, 0x00, 0x00,
}
