// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/cluster.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	tensorflow/core/protobuf/cluster.proto
	tensorflow/core/protobuf/config.proto
	tensorflow/core/protobuf/control_flow.proto
	tensorflow/core/protobuf/debug.proto
	tensorflow/core/protobuf/device_properties.proto
	tensorflow/core/protobuf/master.proto
	tensorflow/core/protobuf/master_service.proto
	tensorflow/core/protobuf/meta_graph.proto
	tensorflow/core/protobuf/named_tensor.proto
	tensorflow/core/protobuf/queue_runner.proto
	tensorflow/core/protobuf/rewriter_config.proto
	tensorflow/core/protobuf/saved_model.proto
	tensorflow/core/protobuf/saver.proto
	tensorflow/core/protobuf/tensor_bundle.proto
	tensorflow/core/protobuf/tensorflow_server.proto
	tensorflow/core/protobuf/worker.proto
	tensorflow/core/protobuf/worker_service.proto

It has these top-level messages:
	JobDef
	ClusterDef
	GPUOptions
	OptimizerOptions
	GraphOptions
	ThreadPoolOptionProto
	RPCOptions
	ConfigProto
	RunOptions
	RunMetadata
	ValuesDef
	CondContextDef
	WhileContextDef
	DebugTensorWatch
	DebugOptions
	DeviceProperties
	DeviceMap
	CreateSessionRequest
	CreateSessionResponse
	ExtendSessionRequest
	ExtendSessionResponse
	RunStepRequest
	RunStepResponse
	PartialRunSetupRequest
	PartialRunSetupResponse
	CloseSessionRequest
	CloseSessionResponse
	ResetRequest
	ResetResponse
	ListDevicesRequest
	ListDevicesResponse
	MetaGraphDef
	CollectionDef
	TensorInfo
	SignatureDef
	AssetFileDef
	NamedTensorProto
	QueueRunnerDef
	AutoParallelOptions
	RewriterConfig
	SavedModel
	SaverDef
	BundleHeaderProto
	BundleEntryProto
	ServerDef
	GetStatusRequest
	GetStatusResponse
	CreateWorkerSessionRequest
	CreateWorkerSessionResponse
	RegisterGraphRequest
	RegisterGraphResponse
	DeregisterGraphRequest
	DeregisterGraphResponse
	CleanupAllRequest
	CleanupAllResponse
	ExecutorOpts
	RunGraphRequest
	RunGraphResponse
	CleanupGraphRequest
	CleanupGraphResponse
	RecvTensorRequest
	RecvTensorResponse
	LoggingRequest
	LabeledStepStats
	LoggingResponse
	TraceOpts
	TracingRequest
	TracingResponse
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Defines a single job in a TensorFlow cluster.
type JobDef struct {
	// The name of this job.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Mapping from task ID to "hostname:port" string.
	//
	// If the `name` field contains "worker", and the `tasks` map contains a
	// mapping from 7 to "example.org:2222", then the device prefix
	// "/job:worker/task:7" will be assigned to "example.org:2222".
	Tasks map[int32]string `protobuf:"bytes,2,rep,name=tasks" json:"tasks,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *JobDef) Reset()                    { *m = JobDef{} }
func (m *JobDef) String() string            { return proto.CompactTextString(m) }
func (*JobDef) ProtoMessage()               {}
func (*JobDef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *JobDef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobDef) GetTasks() map[int32]string {
	if m != nil {
		return m.Tasks
	}
	return nil
}

// Defines a TensorFlow cluster as a set of jobs.
type ClusterDef struct {
	// The jobs that comprise the cluster.
	Job []*JobDef `protobuf:"bytes,1,rep,name=job" json:"job,omitempty"`
}

func (m *ClusterDef) Reset()                    { *m = ClusterDef{} }
func (m *ClusterDef) String() string            { return proto.CompactTextString(m) }
func (*ClusterDef) ProtoMessage()               {}
func (*ClusterDef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ClusterDef) GetJob() []*JobDef {
	if m != nil {
		return m.Job
	}
	return nil
}

func init() {
	proto.RegisterType((*JobDef)(nil), "tensorflow.JobDef")
	proto.RegisterType((*ClusterDef)(nil), "tensorflow.ClusterDef")
}

func init() { proto.RegisterFile("tensorflow/core/protobuf/cluster.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x66, 0x13, 0x53, 0x70, 0x44, 0x90, 0xc5, 0x43, 0x28, 0x08, 0xa5, 0x88, 0xf4, 0xd2, 0x2c,
	0xb4, 0x97, 0xe2, 0xb1, 0xd5, 0x8b, 0xa7, 0x12, 0x3c, 0x79, 0x4b, 0xd2, 0x49, 0x8c, 0x49, 0x76,
	0xca, 0xfe, 0x54, 0xf2, 0x0c, 0xbe, 0xb0, 0x47, 0xd9, 0x8d, 0x10, 0x41, 0x7a, 0x9b, 0x99, 0xef,
	0x77, 0x17, 0x1e, 0x0c, 0x4a, 0x4d, 0xaa, 0x6c, 0xe9, 0x53, 0x14, 0xa4, 0x50, 0x1c, 0x15, 0x19,
	0xca, 0x6d, 0x29, 0x8a, 0xd6, 0x6a, 0x83, 0x2a, 0xf1, 0x07, 0x0e, 0x23, 0x6f, 0xfe, 0xc5, 0x60,
	0xf2, 0x42, 0xf9, 0x13, 0x96, 0x9c, 0xc3, 0x85, 0xcc, 0x3a, 0x8c, 0xd9, 0x8c, 0x2d, 0x2e, 0x53,
	0x3f, 0xf3, 0x35, 0x44, 0x26, 0xd3, 0x8d, 0x8e, 0x83, 0x59, 0xb8, 0xb8, 0x5a, 0xdd, 0x25, 0xa3,
	0x34, 0x19, 0x64, 0xc9, 0xab, 0xc3, 0x9f, 0xa5, 0x51, 0x7d, 0x3a, 0x70, 0xa7, 0x1b, 0x80, 0xf1,
	0xc8, 0x6f, 0x20, 0x6c, 0xb0, 0xf7, 0xae, 0x51, 0xea, 0x46, 0x7e, 0x0b, 0xd1, 0x29, 0x6b, 0x2d,
	0xc6, 0x81, 0x4f, 0x1a, 0x96, 0xc7, 0x60, 0xc3, 0xe6, 0x2b, 0x80, 0xdd, 0x50, 0xd5, 0x15, 0xba,
	0x87, 0xf0, 0x83, 0xf2, 0x98, 0xf9, 0x68, 0xfe, 0x3f, 0x3a, 0x75, 0xf0, 0xd6, 0xc2, 0x94, 0x54,
	0xf5, 0x17, 0x3d, 0xd4, 0xda, 0x28, 0x2b, 0x4d, 0xdd, 0xe1, 0xf6, 0xfa, 0xd7, 0x6f, 0xef, 0x5e,
	0xae, 0xf7, 0xec, 0x6d, 0x57, 0xd5, 0xe6, 0xdd, 0xe6, 0x49, 0x41, 0x9d, 0x38, 0x28, 0xec, 0x1b,
	0x31, 0x2a, 0x97, 0x1a, 0xd5, 0xa9, 0x96, 0xd5, 0xb2, 0x22, 0x71, 0x6c, 0x2a, 0x71, 0xee, 0x3f,
	0xbf, 0x19, 0xcb, 0x27, 0x7e, 0x59, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xb6, 0x31, 0xb4,
	0x75, 0x01, 0x00, 0x00,
}
