// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/worker.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import tensorflow2 "github.com/kuberlab/tfservable-proxy/pkg/tensorflow/core/framework"
import tensorflow13 "github.com/kuberlab/tfservable-proxy/pkg/tensorflow/core/framework"
import tensorflow14 "github.com/kuberlab/tfservable-proxy/pkg/tensorflow/core/framework"
import tensorflow10 "github.com/kuberlab/tfservable-proxy/pkg/tensorflow/core/framework"
import tensorflow4 "github.com/kuberlab/tfservable-proxy/pkg/tensorflow/core/framework"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetStatusRequest struct {
}

func (m *GetStatusRequest) Reset()                    { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()               {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{0} }

type GetStatusResponse struct {
	DeviceAttributes []*tensorflow14.DeviceAttributes `protobuf:"bytes,1,rep,name=device_attributes,json=deviceAttributes" json:"device_attributes,omitempty"`
}

func (m *GetStatusResponse) Reset()                    { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()               {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{1} }

func (m *GetStatusResponse) GetDeviceAttributes() []*tensorflow14.DeviceAttributes {
	if m != nil {
		return m.DeviceAttributes
	}
	return nil
}

type CreateWorkerSessionRequest struct {
	// Sessions are identified by a given handle.
	SessionHandle string `protobuf:"bytes,1,opt,name=session_handle,json=sessionHandle" json:"session_handle,omitempty"`
	// Defines the configuration of a TensorFlow worker.
	ServerDef *ServerDef `protobuf:"bytes,2,opt,name=server_def,json=serverDef" json:"server_def,omitempty"`
}

func (m *CreateWorkerSessionRequest) Reset()                    { *m = CreateWorkerSessionRequest{} }
func (m *CreateWorkerSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateWorkerSessionRequest) ProtoMessage()               {}
func (*CreateWorkerSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{2} }

func (m *CreateWorkerSessionRequest) GetSessionHandle() string {
	if m != nil {
		return m.SessionHandle
	}
	return ""
}

func (m *CreateWorkerSessionRequest) GetServerDef() *ServerDef {
	if m != nil {
		return m.ServerDef
	}
	return nil
}

type CreateWorkerSessionResponse struct {
}

func (m *CreateWorkerSessionResponse) Reset()                    { *m = CreateWorkerSessionResponse{} }
func (m *CreateWorkerSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateWorkerSessionResponse) ProtoMessage()               {}
func (*CreateWorkerSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{3} }

type RegisterGraphRequest struct {
	// Subgraphs are scoped within one session.
	SessionHandle string `protobuf:"bytes,1,opt,name=session_handle,json=sessionHandle" json:"session_handle,omitempty"`
	// "graph_def" has the subgraph of nodes for this worker, with each node
	// having its device_name filled in.
	GraphDef *tensorflow10.GraphDef `protobuf:"bytes,2,opt,name=graph_def,json=graphDef" json:"graph_def,omitempty"`
	// True iff the graph (before partitioning) contains control flow nodes.
	//
	// As of 01/11/2015, this is no longer set by clients.
	HasControlFlow bool `protobuf:"varint,3,opt,name=has_control_flow,json=hasControlFlow" json:"has_control_flow,omitempty"`
	// Configuration options for the session in which this graph was created.
	GraphOptions *GraphOptions `protobuf:"bytes,4,opt,name=graph_options,json=graphOptions" json:"graph_options,omitempty"`
	// Field(s) used by TensorFlow Debugger (tfdbg).
	DebugOptions *DebugOptions `protobuf:"bytes,5,opt,name=debug_options,json=debugOptions" json:"debug_options,omitempty"`
}

func (m *RegisterGraphRequest) Reset()                    { *m = RegisterGraphRequest{} }
func (m *RegisterGraphRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterGraphRequest) ProtoMessage()               {}
func (*RegisterGraphRequest) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{4} }

func (m *RegisterGraphRequest) GetSessionHandle() string {
	if m != nil {
		return m.SessionHandle
	}
	return ""
}

func (m *RegisterGraphRequest) GetGraphDef() *tensorflow10.GraphDef {
	if m != nil {
		return m.GraphDef
	}
	return nil
}

func (m *RegisterGraphRequest) GetHasControlFlow() bool {
	if m != nil {
		return m.HasControlFlow
	}
	return false
}

func (m *RegisterGraphRequest) GetGraphOptions() *GraphOptions {
	if m != nil {
		return m.GraphOptions
	}
	return nil
}

func (m *RegisterGraphRequest) GetDebugOptions() *DebugOptions {
	if m != nil {
		return m.DebugOptions
	}
	return nil
}

type RegisterGraphResponse struct {
	// If the registration succeeds, returns an opaque graph_handle to
	// the master. The master calls RunGraph with graph_handle to
	// compute different steps.
	GraphHandle string `protobuf:"bytes,1,opt,name=graph_handle,json=graphHandle" json:"graph_handle,omitempty"`
}

func (m *RegisterGraphResponse) Reset()                    { *m = RegisterGraphResponse{} }
func (m *RegisterGraphResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterGraphResponse) ProtoMessage()               {}
func (*RegisterGraphResponse) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{5} }

func (m *RegisterGraphResponse) GetGraphHandle() string {
	if m != nil {
		return m.GraphHandle
	}
	return ""
}

type DeregisterGraphRequest struct {
	// The session_handle used when registering the graph. If session_handle is
	// empty, a single global namespace is used.
	SessionHandle string `protobuf:"bytes,2,opt,name=session_handle,json=sessionHandle" json:"session_handle,omitempty"`
	// REQUIRED: graph_handle must be returned by a RegisterGraph call
	// to the same WorkerService.
	GraphHandle string `protobuf:"bytes,1,opt,name=graph_handle,json=graphHandle" json:"graph_handle,omitempty"`
}

func (m *DeregisterGraphRequest) Reset()                    { *m = DeregisterGraphRequest{} }
func (m *DeregisterGraphRequest) String() string            { return proto.CompactTextString(m) }
func (*DeregisterGraphRequest) ProtoMessage()               {}
func (*DeregisterGraphRequest) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{6} }

func (m *DeregisterGraphRequest) GetSessionHandle() string {
	if m != nil {
		return m.SessionHandle
	}
	return ""
}

func (m *DeregisterGraphRequest) GetGraphHandle() string {
	if m != nil {
		return m.GraphHandle
	}
	return ""
}

type DeregisterGraphResponse struct {
}

func (m *DeregisterGraphResponse) Reset()                    { *m = DeregisterGraphResponse{} }
func (m *DeregisterGraphResponse) String() string            { return proto.CompactTextString(m) }
func (*DeregisterGraphResponse) ProtoMessage()               {}
func (*DeregisterGraphResponse) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{7} }

type CleanupAllRequest struct {
	// A list of container names.
	//
	// If 'container' is not empty, releases resoures in the given
	// containers in all devices.
	//
	// If 'container' is empty, releases resources in the default
	// container in all devices.
	Container []string `protobuf:"bytes,1,rep,name=container" json:"container,omitempty"`
}

func (m *CleanupAllRequest) Reset()                    { *m = CleanupAllRequest{} }
func (m *CleanupAllRequest) String() string            { return proto.CompactTextString(m) }
func (*CleanupAllRequest) ProtoMessage()               {}
func (*CleanupAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{8} }

func (m *CleanupAllRequest) GetContainer() []string {
	if m != nil {
		return m.Container
	}
	return nil
}

type CleanupAllResponse struct {
}

func (m *CleanupAllResponse) Reset()                    { *m = CleanupAllResponse{} }
func (m *CleanupAllResponse) String() string            { return proto.CompactTextString(m) }
func (*CleanupAllResponse) ProtoMessage()               {}
func (*CleanupAllResponse) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{9} }

// Options specific to the execution of a single step.
type ExecutorOpts struct {
	RecordCosts    bool `protobuf:"varint,1,opt,name=record_costs,json=recordCosts" json:"record_costs,omitempty"`
	RecordTimeline bool `protobuf:"varint,3,opt,name=record_timeline,json=recordTimeline" json:"record_timeline,omitempty"`
}

func (m *ExecutorOpts) Reset()                    { *m = ExecutorOpts{} }
func (m *ExecutorOpts) String() string            { return proto.CompactTextString(m) }
func (*ExecutorOpts) ProtoMessage()               {}
func (*ExecutorOpts) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{10} }

func (m *ExecutorOpts) GetRecordCosts() bool {
	if m != nil {
		return m.RecordCosts
	}
	return false
}

func (m *ExecutorOpts) GetRecordTimeline() bool {
	if m != nil {
		return m.RecordTimeline
	}
	return false
}

type RunGraphRequest struct {
	// session_handle is the master-generated unique id for this session.
	// If session_handle is non-empty, it must be the same as used when
	// registering the graph. If it is empty, a single global namespace is used to
	// search for the graph_handle.
	SessionHandle string `protobuf:"bytes,8,opt,name=session_handle,json=sessionHandle" json:"session_handle,omitempty"`
	// REQUIRED: graph_handle must be returned by a RegisterGraph call
	// to the same WorkerService.
	GraphHandle string `protobuf:"bytes,1,opt,name=graph_handle,json=graphHandle" json:"graph_handle,omitempty"`
	// A unique ID to distinguish different runs of the same graph.
	//
	// The master generates a global unique `step_id` to distinguish
	// different runs of the graph computation. Subgraphs communicate
	// (e.g., send/recv ops) with each other using `step_id` to
	// distinguish tensors generated by different runs.
	StepId int64 `protobuf:"varint,2,opt,name=step_id,json=stepId" json:"step_id,omitempty"`
	// Options for this step.
	ExecOpts *ExecutorOpts `protobuf:"bytes,5,opt,name=exec_opts,json=execOpts" json:"exec_opts,omitempty"`
	// Runs the graph.
	//
	// Sends the tensors in "send" into the graph before the run and
	// fetches the keys into `RunGraphResponse.recv` after the run.
	Send    []*NamedTensorProto `protobuf:"bytes,3,rep,name=send" json:"send,omitempty"`
	RecvKey []string            `protobuf:"bytes,4,rep,name=recv_key,json=recvKey" json:"recv_key,omitempty"`
	// True if the RunGraphRequest is a partial run request.
	IsPartial bool `protobuf:"varint,6,opt,name=is_partial,json=isPartial" json:"is_partial,omitempty"`
	// True if this is the last partial run request in a sequence of requests.
	IsLastPartialRun bool `protobuf:"varint,7,opt,name=is_last_partial_run,json=isLastPartialRun" json:"is_last_partial_run,omitempty"`
}

func (m *RunGraphRequest) Reset()                    { *m = RunGraphRequest{} }
func (m *RunGraphRequest) String() string            { return proto.CompactTextString(m) }
func (*RunGraphRequest) ProtoMessage()               {}
func (*RunGraphRequest) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{11} }

func (m *RunGraphRequest) GetSessionHandle() string {
	if m != nil {
		return m.SessionHandle
	}
	return ""
}

func (m *RunGraphRequest) GetGraphHandle() string {
	if m != nil {
		return m.GraphHandle
	}
	return ""
}

func (m *RunGraphRequest) GetStepId() int64 {
	if m != nil {
		return m.StepId
	}
	return 0
}

func (m *RunGraphRequest) GetExecOpts() *ExecutorOpts {
	if m != nil {
		return m.ExecOpts
	}
	return nil
}

func (m *RunGraphRequest) GetSend() []*NamedTensorProto {
	if m != nil {
		return m.Send
	}
	return nil
}

func (m *RunGraphRequest) GetRecvKey() []string {
	if m != nil {
		return m.RecvKey
	}
	return nil
}

func (m *RunGraphRequest) GetIsPartial() bool {
	if m != nil {
		return m.IsPartial
	}
	return false
}

func (m *RunGraphRequest) GetIsLastPartialRun() bool {
	if m != nil {
		return m.IsLastPartialRun
	}
	return false
}

type RunGraphResponse struct {
	// A list of tensors corresponding to those requested by
	// `RunGraphRequest.recv_key`.
	Recv []*NamedTensorProto `protobuf:"bytes,1,rep,name=recv" json:"recv,omitempty"`
	// If the request asked for execution stats or cost graph, these are returned
	// here.
	StepStats *tensorflow13.StepStats   `protobuf:"bytes,2,opt,name=step_stats,json=stepStats" json:"step_stats,omitempty"`
	CostGraph *tensorflow2.CostGraphDef `protobuf:"bytes,3,opt,name=cost_graph,json=costGraph" json:"cost_graph,omitempty"`
}

func (m *RunGraphResponse) Reset()                    { *m = RunGraphResponse{} }
func (m *RunGraphResponse) String() string            { return proto.CompactTextString(m) }
func (*RunGraphResponse) ProtoMessage()               {}
func (*RunGraphResponse) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{12} }

func (m *RunGraphResponse) GetRecv() []*NamedTensorProto {
	if m != nil {
		return m.Recv
	}
	return nil
}

func (m *RunGraphResponse) GetStepStats() *tensorflow13.StepStats {
	if m != nil {
		return m.StepStats
	}
	return nil
}

func (m *RunGraphResponse) GetCostGraph() *tensorflow2.CostGraphDef {
	if m != nil {
		return m.CostGraph
	}
	return nil
}

type CleanupGraphRequest struct {
	StepId int64 `protobuf:"varint,1,opt,name=step_id,json=stepId" json:"step_id,omitempty"`
}

func (m *CleanupGraphRequest) Reset()                    { *m = CleanupGraphRequest{} }
func (m *CleanupGraphRequest) String() string            { return proto.CompactTextString(m) }
func (*CleanupGraphRequest) ProtoMessage()               {}
func (*CleanupGraphRequest) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{13} }

func (m *CleanupGraphRequest) GetStepId() int64 {
	if m != nil {
		return m.StepId
	}
	return 0
}

type CleanupGraphResponse struct {
}

func (m *CleanupGraphResponse) Reset()                    { *m = CleanupGraphResponse{} }
func (m *CleanupGraphResponse) String() string            { return proto.CompactTextString(m) }
func (*CleanupGraphResponse) ProtoMessage()               {}
func (*CleanupGraphResponse) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{14} }

type RecvTensorRequest struct {
	// The step in which the tensor will be produced.
	//
	// REQUIRED: This must eventually correspond to the `step_id` passed
	// into a RunGraph call on the same WorkerService.
	StepId int64 `protobuf:"varint,1,opt,name=step_id,json=stepId" json:"step_id,omitempty"`
	// A key that identifies the tensor to be received.
	RendezvousKey string `protobuf:"bytes,2,opt,name=rendezvous_key,json=rendezvousKey" json:"rendezvous_key,omitempty"`
	// If true, use an out-of-band DMA mechanism to transfer the
	// received tensor.
	DmaOk bool `protobuf:"varint,3,opt,name=dma_ok,json=dmaOk" json:"dma_ok,omitempty"`
	// Optional information on client-side device locality.
	ClientLocality *tensorflow14.DeviceLocality `protobuf:"bytes,4,opt,name=client_locality,json=clientLocality" json:"client_locality,omitempty"`
	// Optional information on server-side device locality.
	ServerLocality *tensorflow14.DeviceLocality `protobuf:"bytes,5,opt,name=server_locality,json=serverLocality" json:"server_locality,omitempty"`
	// Optional information needed by the RPC subsystem.
	TransportOptions *google_protobuf.Any `protobuf:"bytes,6,opt,name=transport_options,json=transportOptions" json:"transport_options,omitempty"`
}

func (m *RecvTensorRequest) Reset()                    { *m = RecvTensorRequest{} }
func (m *RecvTensorRequest) String() string            { return proto.CompactTextString(m) }
func (*RecvTensorRequest) ProtoMessage()               {}
func (*RecvTensorRequest) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{15} }

func (m *RecvTensorRequest) GetStepId() int64 {
	if m != nil {
		return m.StepId
	}
	return 0
}

func (m *RecvTensorRequest) GetRendezvousKey() string {
	if m != nil {
		return m.RendezvousKey
	}
	return ""
}

func (m *RecvTensorRequest) GetDmaOk() bool {
	if m != nil {
		return m.DmaOk
	}
	return false
}

func (m *RecvTensorRequest) GetClientLocality() *tensorflow14.DeviceLocality {
	if m != nil {
		return m.ClientLocality
	}
	return nil
}

func (m *RecvTensorRequest) GetServerLocality() *tensorflow14.DeviceLocality {
	if m != nil {
		return m.ServerLocality
	}
	return nil
}

func (m *RecvTensorRequest) GetTransportOptions() *google_protobuf.Any {
	if m != nil {
		return m.TransportOptions
	}
	return nil
}

type RecvTensorResponse struct {
	// The tensor as a proto.
	Tensor *tensorflow4.TensorProto `protobuf:"bytes,1,opt,name=tensor" json:"tensor,omitempty"`
	// If true, this tensor was the output of a dead node, and the
	// content is invalid.
	IsDead bool `protobuf:"varint,2,opt,name=is_dead,json=isDead" json:"is_dead,omitempty"`
	// The time at which tensor was available and started to be returned.
	SendStartMicros int64 `protobuf:"varint,3,opt,name=send_start_micros,json=sendStartMicros" json:"send_start_micros,omitempty"`
	// Optional additional information about how to receive the tensor,
	// e.g. in the event that `RecvTensorRequest.dma_ok` was true.
	TransportOptions *google_protobuf.Any `protobuf:"bytes,4,opt,name=transport_options,json=transportOptions" json:"transport_options,omitempty"`
}

func (m *RecvTensorResponse) Reset()                    { *m = RecvTensorResponse{} }
func (m *RecvTensorResponse) String() string            { return proto.CompactTextString(m) }
func (*RecvTensorResponse) ProtoMessage()               {}
func (*RecvTensorResponse) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{16} }

func (m *RecvTensorResponse) GetTensor() *tensorflow4.TensorProto {
	if m != nil {
		return m.Tensor
	}
	return nil
}

func (m *RecvTensorResponse) GetIsDead() bool {
	if m != nil {
		return m.IsDead
	}
	return false
}

func (m *RecvTensorResponse) GetSendStartMicros() int64 {
	if m != nil {
		return m.SendStartMicros
	}
	return 0
}

func (m *RecvTensorResponse) GetTransportOptions() *google_protobuf.Any {
	if m != nil {
		return m.TransportOptions
	}
	return nil
}

// Out-of-band request to begin or end logging, or
// to retrieve logs for particular steps.
type LoggingRequest struct {
	// If true, RPC logging will be activated.
	RpcLogging bool `protobuf:"varint,1,opt,name=rpc_logging,json=rpcLogging" json:"rpc_logging,omitempty"`
	// If true, discard any saved logging data (for all steps).
	Clear bool `protobuf:"varint,2,opt,name=clear" json:"clear,omitempty"`
	// When set, requests all saved log data pertaining to the step.
	// Any log data retrieved is eliminated from the store and cannot be
	// retrieved again.
	FetchStepId []int64 `protobuf:"varint,3,rep,packed,name=fetch_step_id,json=fetchStepId" json:"fetch_step_id,omitempty"`
}

func (m *LoggingRequest) Reset()                    { *m = LoggingRequest{} }
func (m *LoggingRequest) String() string            { return proto.CompactTextString(m) }
func (*LoggingRequest) ProtoMessage()               {}
func (*LoggingRequest) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{17} }

func (m *LoggingRequest) GetRpcLogging() bool {
	if m != nil {
		return m.RpcLogging
	}
	return false
}

func (m *LoggingRequest) GetClear() bool {
	if m != nil {
		return m.Clear
	}
	return false
}

func (m *LoggingRequest) GetFetchStepId() []int64 {
	if m != nil {
		return m.FetchStepId
	}
	return nil
}

type LabeledStepStats struct {
	StepId    int64                   `protobuf:"varint,1,opt,name=step_id,json=stepId" json:"step_id,omitempty"`
	StepStats *tensorflow13.StepStats `protobuf:"bytes,2,opt,name=step_stats,json=stepStats" json:"step_stats,omitempty"`
}

func (m *LabeledStepStats) Reset()                    { *m = LabeledStepStats{} }
func (m *LabeledStepStats) String() string            { return proto.CompactTextString(m) }
func (*LabeledStepStats) ProtoMessage()               {}
func (*LabeledStepStats) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{18} }

func (m *LabeledStepStats) GetStepId() int64 {
	if m != nil {
		return m.StepId
	}
	return 0
}

func (m *LabeledStepStats) GetStepStats() *tensorflow13.StepStats {
	if m != nil {
		return m.StepStats
	}
	return nil
}

type LoggingResponse struct {
	Step []*LabeledStepStats `protobuf:"bytes,1,rep,name=step" json:"step,omitempty"`
}

func (m *LoggingResponse) Reset()                    { *m = LoggingResponse{} }
func (m *LoggingResponse) String() string            { return proto.CompactTextString(m) }
func (*LoggingResponse) ProtoMessage()               {}
func (*LoggingResponse) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{19} }

func (m *LoggingResponse) GetStep() []*LabeledStepStats {
	if m != nil {
		return m.Step
	}
	return nil
}

type TraceOpts struct {
	// Length of the trace to be taken, in seconds.
	Duration float64 `protobuf:"fixed64,1,opt,name=duration" json:"duration,omitempty"`
	// If true, capture step profile locally in each worker. Currently
	// unimplemented.
	UseStepProfiler bool `protobuf:"varint,2,opt,name=use_step_profiler,json=useStepProfiler" json:"use_step_profiler,omitempty"`
	// If true, capture kernel events from each worker.
	UseKernelProfiler bool `protobuf:"varint,3,opt,name=use_kernel_profiler,json=useKernelProfiler" json:"use_kernel_profiler,omitempty"`
	// If true, capture extended profiling events from TensorFlow process.
	UseExtendedProfiler bool `protobuf:"varint,4,opt,name=use_extended_profiler,json=useExtendedProfiler" json:"use_extended_profiler,omitempty"`
	// If true, capture GPU profiling events locally on each
	// machine. Currently unimplemented.
	UseGpuProfiler bool `protobuf:"varint,5,opt,name=use_gpu_profiler,json=useGpuProfiler" json:"use_gpu_profiler,omitempty"`
	// If true, collect sampled profile events. Currently unimplemented.
	UseSampleProfiler bool `protobuf:"varint,6,opt,name=use_sample_profiler,json=useSampleProfiler" json:"use_sample_profiler,omitempty"`
}

func (m *TraceOpts) Reset()                    { *m = TraceOpts{} }
func (m *TraceOpts) String() string            { return proto.CompactTextString(m) }
func (*TraceOpts) ProtoMessage()               {}
func (*TraceOpts) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{20} }

func (m *TraceOpts) GetDuration() float64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *TraceOpts) GetUseStepProfiler() bool {
	if m != nil {
		return m.UseStepProfiler
	}
	return false
}

func (m *TraceOpts) GetUseKernelProfiler() bool {
	if m != nil {
		return m.UseKernelProfiler
	}
	return false
}

func (m *TraceOpts) GetUseExtendedProfiler() bool {
	if m != nil {
		return m.UseExtendedProfiler
	}
	return false
}

func (m *TraceOpts) GetUseGpuProfiler() bool {
	if m != nil {
		return m.UseGpuProfiler
	}
	return false
}

func (m *TraceOpts) GetUseSampleProfiler() bool {
	if m != nil {
		return m.UseSampleProfiler
	}
	return false
}

// Out-of-band request to configure distributed tracing.
type TracingRequest struct {
	Options *TraceOpts `protobuf:"bytes,1,opt,name=options" json:"options,omitempty"`
}

func (m *TracingRequest) Reset()                    { *m = TracingRequest{} }
func (m *TracingRequest) String() string            { return proto.CompactTextString(m) }
func (*TracingRequest) ProtoMessage()               {}
func (*TracingRequest) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{21} }

func (m *TracingRequest) GetOptions() *TraceOpts {
	if m != nil {
		return m.Options
	}
	return nil
}

type TracingResponse struct {
}

func (m *TracingResponse) Reset()                    { *m = TracingResponse{} }
func (m *TracingResponse) String() string            { return proto.CompactTextString(m) }
func (*TracingResponse) ProtoMessage()               {}
func (*TracingResponse) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{22} }

func init() {
	proto.RegisterType((*GetStatusRequest)(nil), "tensorflow.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "tensorflow.GetStatusResponse")
	proto.RegisterType((*CreateWorkerSessionRequest)(nil), "tensorflow.CreateWorkerSessionRequest")
	proto.RegisterType((*CreateWorkerSessionResponse)(nil), "tensorflow.CreateWorkerSessionResponse")
	proto.RegisterType((*RegisterGraphRequest)(nil), "tensorflow.RegisterGraphRequest")
	proto.RegisterType((*RegisterGraphResponse)(nil), "tensorflow.RegisterGraphResponse")
	proto.RegisterType((*DeregisterGraphRequest)(nil), "tensorflow.DeregisterGraphRequest")
	proto.RegisterType((*DeregisterGraphResponse)(nil), "tensorflow.DeregisterGraphResponse")
	proto.RegisterType((*CleanupAllRequest)(nil), "tensorflow.CleanupAllRequest")
	proto.RegisterType((*CleanupAllResponse)(nil), "tensorflow.CleanupAllResponse")
	proto.RegisterType((*ExecutorOpts)(nil), "tensorflow.ExecutorOpts")
	proto.RegisterType((*RunGraphRequest)(nil), "tensorflow.RunGraphRequest")
	proto.RegisterType((*RunGraphResponse)(nil), "tensorflow.RunGraphResponse")
	proto.RegisterType((*CleanupGraphRequest)(nil), "tensorflow.CleanupGraphRequest")
	proto.RegisterType((*CleanupGraphResponse)(nil), "tensorflow.CleanupGraphResponse")
	proto.RegisterType((*RecvTensorRequest)(nil), "tensorflow.RecvTensorRequest")
	proto.RegisterType((*RecvTensorResponse)(nil), "tensorflow.RecvTensorResponse")
	proto.RegisterType((*LoggingRequest)(nil), "tensorflow.LoggingRequest")
	proto.RegisterType((*LabeledStepStats)(nil), "tensorflow.LabeledStepStats")
	proto.RegisterType((*LoggingResponse)(nil), "tensorflow.LoggingResponse")
	proto.RegisterType((*TraceOpts)(nil), "tensorflow.TraceOpts")
	proto.RegisterType((*TracingRequest)(nil), "tensorflow.TracingRequest")
	proto.RegisterType((*TracingResponse)(nil), "tensorflow.TracingResponse")
}

func init() { proto.RegisterFile("tensorflow/core/protobuf/worker.proto", fileDescriptor15) }

var fileDescriptor15 = []byte{
	// 1249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x06, 0x65, 0x5b, 0x96, 0x46, 0x89, 0x25, 0x31, 0x76, 0xa2, 0xb8, 0x09, 0xea, 0x12, 0x4d,
	0x6b, 0xa4, 0x8d, 0x94, 0xb8, 0x2d, 0x0a, 0x14, 0xe8, 0xc1, 0x91, 0xd3, 0x34, 0x88, 0xdb, 0x18,
	0x74, 0x80, 0x02, 0x39, 0x94, 0x58, 0x91, 0x23, 0x7a, 0x21, 0x8a, 0xcb, 0xee, 0x2e, 0x1d, 0xab,
	0x6f, 0xd1, 0x7b, 0xdf, 0xa2, 0x87, 0xbe, 0x41, 0x6f, 0x7d, 0x9f, 0x1e, 0x8b, 0xfd, 0x21, 0x45,
	0x5b, 0x12, 0x9c, 0xe4, 0xc6, 0x9d, 0xfd, 0x66, 0x76, 0xf6, 0x9b, 0x6f, 0x66, 0x09, 0x0f, 0x24,
	0xa6, 0x82, 0xf1, 0x71, 0xc2, 0xde, 0x0e, 0x42, 0xc6, 0x71, 0x90, 0x71, 0x26, 0xd9, 0x28, 0x1f,
	0x0f, 0xde, 0x32, 0x3e, 0x41, 0xde, 0xd7, 0x6b, 0x17, 0xe6, 0xb0, 0xdd, 0xbb, 0x31, 0x63, 0x71,
	0x52, 0x41, 0x92, 0x74, 0x66, 0x60, 0xbb, 0x0f, 0xaf, 0x46, 0x1b, 0x73, 0x32, 0x45, 0x15, 0x69,
	0x10, 0x32, 0x21, 0x83, 0x98, 0x93, 0xec, 0xec, 0x7a, 0xac, 0x90, 0x98, 0x05, 0x42, 0x12, 0x29,
	0x2c, 0xf6, 0xc9, 0x6a, 0x6c, 0x84, 0xe7, 0x34, 0xc4, 0x80, 0x48, 0xc9, 0xe9, 0x28, 0x97, 0x58,
	0xb8, 0x3c, 0x58, 0xed, 0x52, 0xcd, 0xe2, 0xb3, 0xd5, 0x30, 0xb3, 0xb3, 0x2a, 0x5c, 0x79, 0xfb,
	0x90, 0xa5, 0x63, 0x1a, 0x5b, 0xd8, 0xa7, 0x2b, 0x61, 0x11, 0x8e, 0xf2, 0x02, 0xf5, 0xc5, 0x4a,
	0x54, 0x4a, 0xa6, 0x18, 0x05, 0x97, 0x4e, 0x7e, 0xbc, 0x12, 0x3c, 0xdf, 0x08, 0x04, 0xf2, 0xf3,
	0xa2, 0x58, 0x9e, 0x0b, 0x9d, 0xe7, 0x28, 0x4f, 0x25, 0x91, 0xb9, 0xf0, 0xf1, 0xb7, 0x1c, 0x85,
	0xf4, 0x7e, 0x85, 0x6e, 0xc5, 0x26, 0x32, 0x96, 0x0a, 0x74, 0x5f, 0x40, 0x77, 0x81, 0xbe, 0x9e,
	0xb3, 0xb7, 0xb6, 0xdf, 0x3a, 0xb8, 0xd7, 0x9f, 0x47, 0xef, 0x1f, 0x69, 0xd0, 0x61, 0x89, 0xf1,
	0x3b, 0xd1, 0x15, 0x8b, 0x37, 0x83, 0xdd, 0x21, 0x47, 0x22, 0xf1, 0x17, 0x2d, 0x9b, 0x53, 0x14,
	0x82, 0xb2, 0xd4, 0x9e, 0xee, 0x3e, 0x80, 0x2d, 0x61, 0x2c, 0xc1, 0x19, 0x49, 0xa3, 0x04, 0x7b,
	0xce, 0x9e, 0xb3, 0xdf, 0xf4, 0x6f, 0x5a, 0xeb, 0x8f, 0xda, 0xe8, 0x7e, 0x0d, 0x60, 0x2e, 0x12,
	0x44, 0x38, 0xee, 0xd5, 0xf6, 0x9c, 0xfd, 0xd6, 0xc1, 0x4e, 0x35, 0x91, 0x53, 0xbd, 0x7b, 0x84,
	0x63, 0xbf, 0x29, 0x8a, 0x4f, 0xef, 0x3e, 0x7c, 0xb4, 0xf4, 0x68, 0x73, 0x49, 0xef, 0xcf, 0x1a,
	0x6c, 0xfb, 0x18, 0x53, 0x21, 0x91, 0x3f, 0x57, 0x95, 0x7f, 0xcf, 0xa4, 0x9e, 0x40, 0x53, 0x0b,
	0xa6, 0x92, 0xd3, 0x76, 0x35, 0x27, 0x1d, 0x53, 0xa5, 0xd4, 0x88, 0xed, 0x97, 0xfb, 0x25, 0x74,
	0xce, 0x88, 0x08, 0x42, 0x96, 0x4a, 0xce, 0x92, 0x40, 0xc1, 0x7a, 0x6b, 0x7b, 0xce, 0x7e, 0xe3,
	0x69, 0xad, 0xe7, 0xf8, 0x5b, 0x67, 0x44, 0x0c, 0xcd, 0xd6, 0x0f, 0x09, 0x7b, 0xeb, 0x7e, 0x0f,
	0x37, 0xcd, 0x01, 0x2c, 0x93, 0x94, 0xa5, 0xa2, 0xb7, 0xae, 0x0f, 0xe9, 0x2d, 0x1c, 0xf2, 0xca,
	0xec, 0xfb, 0x37, 0xe2, 0xca, 0x4a, 0xb9, 0x6b, 0x6d, 0x95, 0xee, 0x1b, 0x8b, 0xee, 0x47, 0x0a,
	0x50, 0xba, 0x47, 0x95, 0x95, 0xf7, 0x1d, 0xec, 0x5c, 0x61, 0xc7, 0x8a, 0xe3, 0x13, 0x30, 0xe7,
	0x5c, 0x26, 0xa7, 0xa5, 0x6d, 0x86, 0x1a, 0x6f, 0x04, 0xb7, 0x8f, 0x90, 0xbf, 0x1b, 0xb7, 0xb5,
	0x65, 0xdc, 0xbe, 0xc3, 0x19, 0x77, 0xe1, 0xce, 0xc2, 0x19, 0xb6, 0xb2, 0x4f, 0xa0, 0x3b, 0x4c,
	0x90, 0xa4, 0x79, 0x76, 0x98, 0x24, 0xc5, 0xc9, 0xf7, 0xa0, 0xa9, 0x78, 0x27, 0x34, 0x45, 0xae,
	0xb5, 0xdc, 0xf4, 0xe7, 0x06, 0x6f, 0x1b, 0xdc, 0xaa, 0x8b, 0x0d, 0xf4, 0x06, 0x6e, 0x3c, 0xbb,
	0xc0, 0x30, 0x97, 0x8c, 0xbf, 0xca, 0xa4, 0x50, 0x69, 0x71, 0x0c, 0x19, 0x8f, 0x02, 0x35, 0xb5,
	0x84, 0x4e, 0xab, 0xe1, 0xb7, 0x8c, 0x6d, 0xa8, 0x4c, 0xee, 0xe7, 0xd0, 0xb6, 0x10, 0x49, 0xa7,
	0x98, 0xd0, 0x14, 0x4d, 0x85, 0xfd, 0x2d, 0x63, 0x7e, 0x6d, 0xad, 0xde, 0x3f, 0x35, 0x68, 0xfb,
	0x79, 0x7a, 0x0d, 0x3b, 0x8d, 0x0f, 0x63, 0xc7, 0xbd, 0x03, 0x9b, 0x7a, 0x58, 0xd2, 0x48, 0x13,
	0xbc, 0xe6, 0xd7, 0xd5, 0xf2, 0x45, 0xe4, 0x7e, 0x03, 0x4d, 0xbc, 0xc0, 0x50, 0x89, 0x62, 0xa9,
	0x22, 0xaa, 0xf7, 0xf5, 0x1b, 0x0a, 0xaa, 0x6f, 0xfe, 0x18, 0xd6, 0x05, 0xa6, 0x51, 0x6f, 0x6d,
	0x71, 0x08, 0xfc, 0xac, 0x46, 0xd3, 0x6b, 0xbd, 0x3e, 0x51, 0x63, 0xc6, 0xd7, 0x48, 0xf7, 0x2e,
	0x34, 0x38, 0x86, 0xe7, 0xc1, 0x04, 0x67, 0xbd, 0x75, 0x4d, 0xf7, 0xa6, 0x5a, 0xbf, 0xc4, 0x99,
	0x7b, 0x1f, 0x80, 0x8a, 0x20, 0x23, 0x5c, 0x52, 0x92, 0xf4, 0xea, 0x9a, 0x9e, 0x26, 0x15, 0x27,
	0xc6, 0xe0, 0x3e, 0x82, 0x5b, 0x54, 0x04, 0x09, 0x11, 0xb2, 0xc0, 0x04, 0x3c, 0x4f, 0x7b, 0x9b,
	0x1a, 0xd7, 0xa1, 0xe2, 0x98, 0x08, 0x69, 0xb1, 0x7e, 0x9e, 0x7a, 0x7f, 0x39, 0xd0, 0x99, 0x13,
	0x69, 0x45, 0xfa, 0x18, 0xd6, 0xd5, 0x69, 0xcb, 0x86, 0xd6, 0x62, 0xbe, 0x0a, 0xa9, 0x67, 0x4c,
	0xf9, 0xbc, 0x2c, 0x9d, 0x31, 0x12, 0x33, 0x35, 0x27, 0x85, 0xdf, 0x14, 0xc5, 0xa7, 0xfb, 0x2d,
	0xc0, 0xfc, 0x01, 0xd3, 0x95, 0xbe, 0xc2, 0xa7, 0x52, 0x45, 0x39, 0x09, 0x9a, 0x61, 0xb1, 0xf2,
	0xfa, 0x70, 0xcb, 0x0a, 0xee, 0x92, 0x02, 0x2a, 0x75, 0x73, 0xaa, 0x75, 0xf3, 0x6e, 0xc3, 0xf6,
	0x65, 0xbc, 0x95, 0xe8, 0xdf, 0x35, 0xe8, 0xfa, 0x18, 0x9e, 0x9b, 0x0b, 0x5d, 0x17, 0x46, 0x29,
	0x8c, 0x63, 0x1a, 0xe1, 0xef, 0xe7, 0x2c, 0x17, 0xba, 0x36, 0xb6, 0xff, 0xe6, 0x56, 0x55, 0xa1,
	0x1d, 0xa8, 0x47, 0x53, 0x12, 0xb0, 0x89, 0x15, 0xef, 0x46, 0x34, 0x25, 0xaf, 0x26, 0xee, 0x10,
	0xda, 0x61, 0x42, 0x31, 0x95, 0x41, 0xc2, 0x42, 0x92, 0x50, 0x39, 0xb3, 0x33, 0x69, 0x77, 0xf1,
	0x55, 0x38, 0xb6, 0x08, 0x7f, 0xcb, 0xb8, 0x14, 0x6b, 0x15, 0xc4, 0x0e, 0xf3, 0x32, 0xc8, 0xc6,
	0xf5, 0x41, 0x8c, 0x4b, 0x19, 0xe4, 0x10, 0xba, 0x92, 0x93, 0x54, 0x64, 0x8c, 0xcb, 0x72, 0xc0,
	0xd5, 0xed, 0x10, 0x36, 0xff, 0x21, 0xfd, 0xe2, 0x3d, 0xec, 0x1f, 0xa6, 0x33, 0xbf, 0x53, 0xc2,
	0x8b, 0x01, 0xf7, 0xaf, 0x03, 0x6e, 0x95, 0x39, 0xab, 0x9c, 0x01, 0xd4, 0x4d, 0x1a, 0x9a, 0xb9,
	0xd6, 0xc1, 0x9d, 0x6a, 0x56, 0x55, 0xd9, 0x58, 0x98, 0xe2, 0x9a, 0x8a, 0x20, 0x42, 0x62, 0x5a,
	0xad, 0xe1, 0xd7, 0xa9, 0x38, 0x42, 0x12, 0xb9, 0x0f, 0xa1, 0xab, 0x3a, 0x41, 0x29, 0x8a, 0xcb,
	0x60, 0x4a, 0x43, 0xce, 0x84, 0xe6, 0x73, 0xcd, 0x6f, 0xab, 0x8d, 0x53, 0x65, 0xff, 0x49, 0x9b,
	0x97, 0xdf, 0x67, 0xfd, 0xbd, 0xee, 0x33, 0x81, 0xad, 0x63, 0x16, 0xc7, 0x34, 0x8d, 0x0b, 0x15,
	0x7c, 0x0c, 0x2d, 0x9e, 0x85, 0x41, 0x62, 0xac, 0x76, 0x5a, 0x01, 0xcf, 0x42, 0x8b, 0x73, 0xb7,
	0x61, 0x23, 0x4c, 0x90, 0x70, 0x9b, 0xb8, 0x59, 0xb8, 0x1e, 0xdc, 0x1c, 0xa3, 0x0c, 0xcf, 0x82,
	0x42, 0x42, 0xaa, 0xe9, 0xd7, 0xfc, 0x96, 0x36, 0x9e, 0x1a, 0x39, 0x12, 0xe8, 0x1c, 0x93, 0x11,
	0x26, 0x18, 0x95, 0x6d, 0xb1, 0x5a, 0x74, 0x1f, 0xd4, 0x5a, 0xde, 0x10, 0xda, 0xe5, 0x7d, 0xe6,
	0x5d, 0xad, 0xf6, 0x97, 0x75, 0xf5, 0xd5, 0x6c, 0x7c, 0x8d, 0xf4, 0xfe, 0xa8, 0x41, 0xf3, 0x35,
	0x27, 0x21, 0xea, 0x29, 0xb6, 0x0b, 0x8d, 0x28, 0xe7, 0x44, 0xf1, 0xa5, 0x53, 0x74, 0xfc, 0x72,
	0xad, 0xaa, 0x95, 0x0b, 0x34, 0x77, 0xce, 0x38, 0x1b, 0xd3, 0x04, 0x0b, 0x5e, 0xda, 0xb9, 0x40,
	0x15, 0xf8, 0xc4, 0x9a, 0xdd, 0x3e, 0xdc, 0x52, 0xd8, 0x09, 0xf2, 0x14, 0x93, 0x39, 0xda, 0xf4,
	0x8a, 0x0a, 0xf3, 0x52, 0xef, 0x94, 0xf8, 0x03, 0xd8, 0x51, 0x78, 0xbc, 0x90, 0xaa, 0xcb, 0xa2,
	0xb9, 0xc7, 0xba, 0xf6, 0x50, 0xc1, 0x9e, 0xd9, 0xbd, 0xd2, 0x67, 0x1f, 0x3a, 0xca, 0x27, 0xce,
	0xf2, 0x39, 0x7c, 0xc3, 0xbc, 0x24, 0xb9, 0xc0, 0xe7, 0x59, 0x7e, 0x35, 0x1b, 0x41, 0xa6, 0x59,
	0x82, 0x73, 0x70, 0xbd, 0xcc, 0xe6, 0x54, 0xef, 0x14, 0x78, 0xef, 0x10, 0xb6, 0x14, 0x25, 0x15,
	0xa1, 0x0c, 0x60, 0xb3, 0xd0, 0x9c, 0xb3, 0x58, 0x9d, 0x92, 0x3f, 0xbf, 0x40, 0x79, 0x5d, 0x68,
	0x97, 0x21, 0x4c, 0x6d, 0x9e, 0x4a, 0xd8, 0x65, 0x3c, 0xae, 0xfa, 0x45, 0x54, 0x48, 0x9e, 0xa7,
	0xea, 0x1d, 0x7c, 0x7a, 0xc3, 0xfc, 0x83, 0xe9, 0xce, 0x11, 0x27, 0xce, 0x9b, 0x61, 0x4c, 0xe5,
	0x59, 0x3e, 0xea, 0x87, 0x6c, 0x3a, 0x88, 0x38, 0xce, 0x26, 0x95, 0x9f, 0xd6, 0x47, 0xaa, 0xd7,
	0x69, 0x1a, 0x3f, 0x8a, 0xd9, 0x20, 0x9b, 0xc4, 0x83, 0x55, 0xff, 0xb9, 0xff, 0x39, 0xce, 0xa8,
	0xae, 0x17, 0x5f, 0xfd, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xaf, 0xea, 0x02, 0xaf, 0x0c, 0x00,
	0x00,
}
