// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow_serving/apis/internal/serialized_input.proto

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	tensorflow_serving/apis/internal/serialized_input.proto

It has these top-level messages:
	SerializedExampleList
	SerializedExampleListWithContext
	SerializedInput
*/
package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SerializedExampleList struct {
	Examples [][]byte `protobuf:"bytes,1,rep,name=examples,proto3" json:"examples,omitempty"`
}

func (m *SerializedExampleList) Reset()                    { *m = SerializedExampleList{} }
func (m *SerializedExampleList) String() string            { return proto.CompactTextString(m) }
func (*SerializedExampleList) ProtoMessage()               {}
func (*SerializedExampleList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SerializedExampleList) GetExamples() [][]byte {
	if m != nil {
		return m.Examples
	}
	return nil
}

type SerializedExampleListWithContext struct {
	Examples [][]byte `protobuf:"bytes,1,rep,name=examples,proto3" json:"examples,omitempty"`
	Context  []byte   `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
}

func (m *SerializedExampleListWithContext) Reset()         { *m = SerializedExampleListWithContext{} }
func (m *SerializedExampleListWithContext) String() string { return proto.CompactTextString(m) }
func (*SerializedExampleListWithContext) ProtoMessage()    {}
func (*SerializedExampleListWithContext) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1}
}

func (m *SerializedExampleListWithContext) GetExamples() [][]byte {
	if m != nil {
		return m.Examples
	}
	return nil
}

func (m *SerializedExampleListWithContext) GetContext() []byte {
	if m != nil {
		return m.Context
	}
	return nil
}

type SerializedInput struct {
	// Types that are valid to be assigned to Kind:
	//	*SerializedInput_ExampleList
	//	*SerializedInput_ExampleListWithContext
	Kind isSerializedInput_Kind `protobuf_oneof:"kind"`
}

func (m *SerializedInput) Reset()                    { *m = SerializedInput{} }
func (m *SerializedInput) String() string            { return proto.CompactTextString(m) }
func (*SerializedInput) ProtoMessage()               {}
func (*SerializedInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isSerializedInput_Kind interface {
	isSerializedInput_Kind()
}

type SerializedInput_ExampleList struct {
	ExampleList *SerializedExampleList `protobuf:"bytes,1,opt,name=example_list,json=exampleList,oneof"`
}
type SerializedInput_ExampleListWithContext struct {
	ExampleListWithContext *SerializedExampleListWithContext `protobuf:"bytes,2,opt,name=example_list_with_context,json=exampleListWithContext,oneof"`
}

func (*SerializedInput_ExampleList) isSerializedInput_Kind()            {}
func (*SerializedInput_ExampleListWithContext) isSerializedInput_Kind() {}

func (m *SerializedInput) GetKind() isSerializedInput_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *SerializedInput) GetExampleList() *SerializedExampleList {
	if x, ok := m.GetKind().(*SerializedInput_ExampleList); ok {
		return x.ExampleList
	}
	return nil
}

func (m *SerializedInput) GetExampleListWithContext() *SerializedExampleListWithContext {
	if x, ok := m.GetKind().(*SerializedInput_ExampleListWithContext); ok {
		return x.ExampleListWithContext
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SerializedInput) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SerializedInput_OneofMarshaler, _SerializedInput_OneofUnmarshaler, _SerializedInput_OneofSizer, []interface{}{
		(*SerializedInput_ExampleList)(nil),
		(*SerializedInput_ExampleListWithContext)(nil),
	}
}

func _SerializedInput_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SerializedInput)
	// kind
	switch x := m.Kind.(type) {
	case *SerializedInput_ExampleList:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExampleList); err != nil {
			return err
		}
	case *SerializedInput_ExampleListWithContext:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExampleListWithContext); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SerializedInput.Kind has unexpected type %T", x)
	}
	return nil
}

func _SerializedInput_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SerializedInput)
	switch tag {
	case 1: // kind.example_list
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SerializedExampleList)
		err := b.DecodeMessage(msg)
		m.Kind = &SerializedInput_ExampleList{msg}
		return true, err
	case 2: // kind.example_list_with_context
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SerializedExampleListWithContext)
		err := b.DecodeMessage(msg)
		m.Kind = &SerializedInput_ExampleListWithContext{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SerializedInput_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SerializedInput)
	// kind
	switch x := m.Kind.(type) {
	case *SerializedInput_ExampleList:
		s := proto.Size(x.ExampleList)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SerializedInput_ExampleListWithContext:
		s := proto.Size(x.ExampleListWithContext)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*SerializedExampleList)(nil), "tensorflow.serving.internal.SerializedExampleList")
	proto.RegisterType((*SerializedExampleListWithContext)(nil), "tensorflow.serving.internal.SerializedExampleListWithContext")
	proto.RegisterType((*SerializedInput)(nil), "tensorflow.serving.internal.SerializedInput")
}

func init() {
	proto.RegisterFile("tensorflow_serving/apis/internal/serialized_input.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xb1, 0x4b, 0xc3, 0x40,
	0x14, 0xc6, 0x7b, 0x2a, 0x55, 0x2e, 0x01, 0x21, 0xa0, 0x44, 0x5d, 0x42, 0xa6, 0x2c, 0xbd, 0x83,
	0x74, 0x70, 0x72, 0xa9, 0x08, 0x15, 0x1d, 0x24, 0x0e, 0x15, 0x97, 0x90, 0x36, 0xcf, 0xe4, 0x91,
	0xf4, 0x2e, 0xdc, 0x5d, 0x6d, 0xed, 0x1f, 0xed, 0xec, 0x28, 0xda, 0xb4, 0xc9, 0x10, 0x2a, 0x8e,
	0x1f, 0x77, 0xbf, 0xf7, 0x7d, 0xdf, 0xdd, 0xa3, 0xd7, 0x06, 0x84, 0x96, 0xea, 0xad, 0x94, 0xcb,
	0x58, 0x83, 0x7a, 0x47, 0x91, 0xf1, 0xa4, 0x42, 0xcd, 0x51, 0x18, 0x50, 0x22, 0x29, 0xb9, 0x06,
	0x85, 0x49, 0x89, 0x6b, 0x48, 0x63, 0x14, 0xd5, 0xc2, 0xb0, 0x4a, 0x49, 0x23, 0x9d, 0xab, 0x06,
	0x64, 0x35, 0xc8, 0xb6, 0x8c, 0x3f, 0xa4, 0x67, 0xcf, 0x3b, 0xec, 0x6e, 0x95, 0xcc, 0xab, 0x12,
	0x1e, 0x51, 0x1b, 0xe7, 0x92, 0x9e, 0xc0, 0x46, 0x6a, 0x97, 0x78, 0x87, 0x81, 0x1d, 0xed, 0xb4,
	0xff, 0x42, 0xbd, 0x4e, 0x68, 0x82, 0x26, 0xbf, 0x95, 0xc2, 0xc0, 0x6a, 0x2f, 0xef, 0xb8, 0xf4,
	0x78, 0xb6, 0xb9, 0xe6, 0x1e, 0x78, 0x24, 0xb0, 0xa3, 0xad, 0xf4, 0x3f, 0x09, 0x3d, 0x6d, 0x46,
	0xdf, 0xff, 0xb4, 0x70, 0x26, 0xd4, 0xae, 0xc9, 0xb8, 0x44, 0x6d, 0x5c, 0xe2, 0x91, 0xc0, 0x0a,
	0x43, 0xb6, 0xa7, 0x16, 0xeb, 0x8c, 0x37, 0xee, 0x45, 0x16, 0xb4, 0x2a, 0xae, 0xe9, 0x45, 0x7b,
	0x70, 0xbc, 0x44, 0x93, 0xc7, 0xed, 0x60, 0x56, 0x78, 0xf3, 0x7f, 0x97, 0xd6, 0x23, 0x8c, 0x7b,
	0xd1, 0x39, 0x74, 0x9e, 0x8c, 0xfa, 0xf4, 0xa8, 0x40, 0x91, 0x8e, 0x9e, 0x5e, 0x1f, 0x32, 0x34,
	0xf9, 0x62, 0xca, 0x66, 0x72, 0xce, 0x53, 0x05, 0x1f, 0x05, 0x6f, 0x2c, 0x07, 0xb5, 0xe5, 0x20,
	0x93, 0xbc, 0x2a, 0x32, 0xfe, 0xd7, 0x0a, 0x7c, 0x11, 0x32, 0xed, 0xff, 0xfe, 0xfa, 0xf0, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0xe3, 0x0d, 0xaa, 0x89, 0x30, 0x02, 0x00, 0x00,
}
